package fe.buildsrc

import groovy.lang.Closure
import groovy.util.IndentPrinter
import groovy.xml.MarkupBuilder
import org.gradle.api.DefaultTask
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.withGroovyBuilder
import java.io.File

abstract class LocaleConfigTask : DefaultTask() {
    @get:Input
    abstract val locales: ListProperty<String>

    @get:Input
    abstract val outputFile: Property<File>

    private val indent = "\t"

    @TaskAction
    fun fetch() {
        outputFile.get().bufferedWriter().use { writer ->
            val xml = MarkupBuilder(IndentPrinter(writer, indent, true))
            xml.doubleQuotes = true
            xml.mkp.xmlDeclaration(mapOf(
                "version" to "1.0",
                "encoding" to "utf-8"
            ))
            xml.mkp.comment("This file is generated by LocaleConfigTask")
            xml.mkp.yield("\n")
            xml.withGroovyBuilder {
                "locale-config"("xmlns:android" to "http://schemas.android.com/apk/res/android") {
                    for (locale in locales.get()) {
                        "locale"("android:name" to locale)
                    }
                }
            }
        }
    }
}
