package fe.linksheet

val redirectResolverApiUrl = "https://rhxxkicztujvnyntzmmb.functions.supabase.co/redirector"
val redirectResolverApiKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoeHhraWN6dHVqdm55bnR6bW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzc5MjkxMzAsImV4cCI6MTk5MzUwNTEzMH0.KM5GBWk3DzZu5Zx4gcCbIwNPKnPZT8Qi-7_JKwjimsE"