package fe.linksheet.util.mime

object KnownMimeTypes {
    val mimeTypeToExtensions: Map<String, Array<String>> = mapOf(
        "application/andrew-inset" to arrayOf("ez"),
        "application/applixware" to arrayOf("aw"),
        "text/iso19139+xml" to arrayOf("iso19139"),
        "application/atom+xml" to arrayOf("atom"),
        "application/atomcat+xml" to arrayOf("atomcat"),
        "application/atomsvc+xml" to arrayOf("atomsvc"),
        "application/x-bat" to arrayOf("bat", "cmd"),
        "application/bizagi-modeler" to arrayOf("bpm"),
        "application/cbor" to arrayOf("cbor"),
        "application/ccxml+xml" to arrayOf("ccxml"),
        "application/coreldraw" to arrayOf("cdr"),
        "application/cu-seeme" to arrayOf("cu"),
        "application/dash+xml" to arrayOf("mpd"),
        "application/davmount+xml" to arrayOf("davmount"),
        "application/x-dbf" to arrayOf("dbf", "dbase", "dbase3"),
        "application/dita+xml;format=map" to arrayOf("ditamap"),
        "application/dita+xml;format=topic" to arrayOf("dita"),
        "application/dita+xml;format=val" to arrayOf("ditaval"),
        "application/x-dvd-ifo" to arrayOf("ifo", "bup"),
        "application/ecmascript" to arrayOf("ecma"),
        "application/emma+xml" to arrayOf("emma"),
        "application/envi.hdr" to arrayOf("hdr"),
        "application/epub+zip" to arrayOf("epub"),
        "application/fits" to arrayOf("fits", "fit", "fts"),
        "application/font-tdpfr" to arrayOf("pfr"),
        "application/hyperstudio" to arrayOf("stk"),
        "application/illustrator" to arrayOf("ai"),
        "application/java-archive" to arrayOf("jar"),
        "application/vnd.android.package-archive" to arrayOf("apk"),
        "application/x-tika-java-enterprise-archive" to arrayOf("ear"),
        "application/x-tika-java-web-archive" to arrayOf("war"),
        "application/java-serialized-object" to arrayOf("ser"),
        "application/javascript" to arrayOf("js"),
        "application/json" to arrayOf("json"),
        "application/manifest+json" to arrayOf("webmanifest"),
        "application/java-vm" to arrayOf("class"),
        "application/x-java-jnilib" to arrayOf("jnilib"),
        "application/vnd.java.hprof " to arrayOf("hprof"),
        "application/vnd.java.hprof.text" to arrayOf("hprof.txt"),
        "application/lost+xml" to arrayOf("lostxml"),
        "application/mac-binhex40" to arrayOf("hqx"),
        "application/mac-compactpro" to arrayOf("cpt"),
        "application/marc" to arrayOf("mrc"),
        "application/mathematica" to arrayOf("ma", "nb", "mb"),
        "application/vnd.wolfram.wl" to arrayOf("wl"),
        "application/mathml+xml" to arrayOf("mathml"),
        "application/mbox" to arrayOf("mbox"),
        "application/mediaservercontrol+xml" to arrayOf("mscml"),
        "application/vnd.mif" to arrayOf("mif"),
        "application/mp4" to arrayOf("mp4s"),
        "application/msword" to arrayOf("doc", "dot"),
        "application/mxf" to arrayOf("mxf"),
        "application/octet-stream" to arrayOf(
            "bin",
            "dms",
            "lha",
            "lrf",
            "lzh",
            "so",
            "dist",
            "distz",
            "pkg",
            "bpk",
            "dump",
            "elc",
            "deploy"
        ),
        "application/oda" to arrayOf("oda"),
        "application/oebps-package+xml" to arrayOf("opf"),
        "application/ogg" to arrayOf("ogx"),
        "application/onenote" to arrayOf("onetmp"),
        "application/onenote;format=one" to arrayOf("one"),
        "application/onenote;format=onetoc2" to arrayOf("onetoc", "onetoc2"),
        "application/onenote; format=package" to arrayOf("onepkg"),
        "application/patch-ops-error+xml" to arrayOf("xer"),
        "application/pdf" to arrayOf("pdf"),
        "application/pgp-encrypted" to arrayOf("pgp", "gpg"),
        "application/pgp-signature" to arrayOf("asc", "sig"),
        "application/pics-rules" to arrayOf("prf"),
        "application/pkcs10" to arrayOf("p10"),
        "application/pkcs7-mime" to arrayOf("p7m", "p7c"),
        "application/pkcs7-signature" to arrayOf("p7s"),
        "application/timestamped-data" to arrayOf("tsd"),
        "application/pkix-cert" to arrayOf("cer"),
        "application/pkix-crl" to arrayOf("crl"),
        "application/pkix-pkipath" to arrayOf("pkipath"),
        "application/pkixcmp" to arrayOf("pki"),
        "application/pls+xml" to arrayOf("pls"),
        "application/postscript" to arrayOf("ps", "eps", "epsf", "epsi"),
        "application/prs.cww" to arrayOf("cww"),
        "application/rdf+xml" to arrayOf("rdf", "owl", "df$", "wl$", "xmp"),
        "application/reginfo+xml" to arrayOf("rif"),
        "application/relax-ng-compact-syntax" to arrayOf("rnc"),
        "application/resource-lists+xml" to arrayOf("rl"),
        "application/resource-lists-diff+xml" to arrayOf("rld"),
        "application/rls-services+xml" to arrayOf("rs"),
        "application/rsd+xml" to arrayOf("rsd"),
        "application/rss+xml" to arrayOf("rss"),
        "application/rtf" to arrayOf("rtf"),
        "application/sbml+xml" to arrayOf("sbml"),
        "application/scvp-cv-request" to arrayOf("scq"),
        "application/scvp-cv-response" to arrayOf("scs"),
        "application/scvp-vp-request" to arrayOf("spq"),
        "application/scvp-vp-response" to arrayOf("spp"),
        "application/sdp" to arrayOf("sdp"),
        "application/sereal" to arrayOf("srl"),
        "application/set-payment-initiation" to arrayOf("setpay"),
        "application/set-registration-initiation" to arrayOf("setreg"),
        "application/shf+xml" to arrayOf("shf"),
        "application/smil+xml" to arrayOf("smi", "smil", "sml"),
        "application/sldworks" to arrayOf("sldprt", "sldasm", "slddrw"),
        "application/sparql-query" to arrayOf("rq"),
        "application/sparql-results+xml" to arrayOf("srx"),
        "application/srgs" to arrayOf("gram"),
        "application/srgs+xml" to arrayOf("grxml"),
        "application/ssml+xml" to arrayOf("ssml"),
        "application/vnd.3gpp.pic-bw-large" to arrayOf("plb"),
        "application/vnd.3gpp.pic-bw-small" to arrayOf("psb"),
        "application/vnd.3gpp.pic-bw-var" to arrayOf("pvb"),
        "application/vnd.3gpp2.tcap" to arrayOf("tcap"),
        "application/vnd.3m.post-it-notes" to arrayOf("pwn"),
        "application/vnd.accpac.simply.aso" to arrayOf("aso"),
        "application/vnd.accpac.simply.imp" to arrayOf("imp"),
        "application/vnd.acucobol" to arrayOf("acu"),
        "application/vnd.acucorp" to arrayOf("atc", "acutc"),
        "application/vnd.adobe.air-application-installer-package+zip" to arrayOf("air"),
        "application/vnd.adobe.aftereffects.project" to arrayOf("aep"),
        "application/vnd.adobe.aftereffects.template" to arrayOf("aet"),
        "application/vnd.adobe.xdp+xml" to arrayOf("xdp"),
        "application/vnd.adobe.xfdf" to arrayOf("xfdf"),
        "application/vnd.airzip.filesecure.azf" to arrayOf("azf"),
        "application/vnd.airzip.filesecure.azs" to arrayOf("azs"),
        "application/vnd.amazon.ebook" to arrayOf("azw"),
        "application/vnd.americandynamics.acc" to arrayOf("acc"),
        "application/vnd.amiga.ami" to arrayOf("ami"),
        "application/vnd.anser-web-certificate-issue-initiation" to arrayOf("cii"),
        "application/vnd.anser-web-funds-transfer-initiation" to arrayOf("fti"),
        "application/vnd.antix.game-component" to arrayOf("atx"),
        "application/vnd.apple.installer+xml" to arrayOf("mpkg"),
        "application/vnd.apple.keynote" to arrayOf("key"),
        "application/vnd.apple.mpegurl" to arrayOf("m3u8"),
        "application/vnd.apple.pages" to arrayOf("pages"),
        "application/vnd.apple.numbers" to arrayOf("numbers"),
        "application/vnd.arastra.swi" to arrayOf("swi"),
        "application/vnd.blueice.multipass" to arrayOf("mpm"),
        "application/vnd.bmi" to arrayOf("bmi"),
        "application/vnd.businessobjects" to arrayOf("rep"),
        "application/vnd.chemdraw+xml" to arrayOf("cdxml"),
        "application/vnd.chipnuts.karaoke-mmd" to arrayOf("mmd"),
        "application/vnd.cinderella" to arrayOf("cdy"),
        "application/vnd.claymore" to arrayOf("cla"),
        "application/vnd.clonk.c4group" to arrayOf("c4g", "c4d", "c4f", "c4p", "c4u"),
        "application/vnd.commonspace" to arrayOf("csp"),
        "application/vnd.contact.cmsg" to arrayOf("cdbcmsg"),
        "application/vnd.cosmocaller" to arrayOf("cmc"),
        "application/vnd.crick.clicker" to arrayOf("clkx"),
        "application/vnd.crick.clicker.keyboard" to arrayOf("clkk"),
        "application/vnd.crick.clicker.palette" to arrayOf("clkp"),
        "application/vnd.crick.clicker.template" to arrayOf("clkt"),
        "application/vnd.crick.clicker.wordbank" to arrayOf("clkw"),
        "application/vnd.criticaltools.wbs+xml" to arrayOf("wbs"),
        "application/vnd.ctc-posml" to arrayOf("pml"),
        "application/vnd.cups-ppd" to arrayOf("ppd"),
        "application/vnd.curl.car" to arrayOf("car"),
        "application/vnd.curl.pcurl" to arrayOf("pcurl"),
        "application/vnd.data-vision.rdz" to arrayOf("rdz"),
        "application/vnd.denovo.fcselayout-link" to arrayOf("fe_launch"),
        "application/vnd.dna" to arrayOf("dna"),
        "application/vnd.dolby.mlp" to arrayOf("mlp"),
        "application/vnd.dpgraph" to arrayOf("dpg"),
        "application/vnd.dreamfactory" to arrayOf("dfac"),
        "application/vnd.dynageo" to arrayOf("geo"),
        "application/vnd.ecowin.chart" to arrayOf("mag"),
        "application/vnd.enliven" to arrayOf("nml"),
        "application/vnd.epson.esf" to arrayOf("esf"),
        "application/vnd.epson.msf" to arrayOf("msf"),
        "application/vnd.epson.quickanime" to arrayOf("qam"),
        "application/vnd.epson.salt" to arrayOf("slt"),
        "application/vnd.epson.ssf" to arrayOf("ssf"),
        "application/vnd.eszigno3+xml" to arrayOf("es3", "et3"),
        "application/vnd.etsi.asic-e+zip" to arrayOf("asice"),
        "application/vnd.etsi.asic-s+zip" to arrayOf("asics"),
        "application/vnd.ezpix-album" to arrayOf("ez2"),
        "application/vnd.ezpix-package" to arrayOf("ez3"),
        "application/vnd.fdf" to arrayOf("fdf"),
        "application/vnd.fdsn.mseed" to arrayOf("mseed"),
        "application/vnd.fdsn.seed" to arrayOf("seed", "dataless"),
        "application/vnd.flographit" to arrayOf("gph"),
        "application/vnd.fluxtime.clip" to arrayOf("ftc"),
        "application/vnd.framemaker" to arrayOf("fm", "frame", "maker", "book"),
        "application/vnd.frogans.fnc" to arrayOf("fnc"),
        "application/vnd.frogans.ltf" to arrayOf("ltf"),
        "application/vnd.fsc.weblaunch" to arrayOf("fsc"),
        "application/vnd.fujitsu.oasys" to arrayOf("oas"),
        "application/vnd.fujitsu.oasys2" to arrayOf("oa2"),
        "application/vnd.fujitsu.oasys3" to arrayOf("oa3"),
        "application/vnd.fujitsu.oasysgp" to arrayOf("fg5"),
        "application/vnd.fujitsu.oasysprs" to arrayOf("bh2"),
        "application/vnd.fujixerox.ddd" to arrayOf("ddd"),
        "application/vnd.fujixerox.docuworks" to arrayOf("xdw"),
        "application/vnd.fujixerox.docuworks.binder" to arrayOf("xbd"),
        "application/vnd.fuzzysheet" to arrayOf("fzs"),
        "application/vnd.genomatix.tuxedo" to arrayOf("txd"),
        "application/vnd.geogebra.file" to arrayOf("ggb"),
        "application/vnd.geogebra.tool" to arrayOf("ggt"),
        "application/vnd.geometry-explorer" to arrayOf("gex", "gre"),
        "application/vnd.gmx" to arrayOf("gmx"),
        "application/vnd.google-earth.kml+xml" to arrayOf("kml"),
        "application/vnd.google-earth.kmz" to arrayOf("kmz"),
        "application/vnd.grafeq" to arrayOf("gqf", "gqs"),
        "application/vnd.groove-account" to arrayOf("gac"),
        "application/vnd.groove-help" to arrayOf("ghf"),
        "application/vnd.groove-identity-message" to arrayOf("gim"),
        "application/vnd.groove-injector" to arrayOf("grv"),
        "application/vnd.groove-tool-message" to arrayOf("gtm"),
        "application/vnd.groove-tool-template" to arrayOf("tpl"),
        "application/vnd.groove-vcard" to arrayOf("vcg"),
        "application/vnd.handheld-entertainment+xml" to arrayOf("zmm"),
        "application/vnd.hbci" to arrayOf("hbci"),
        "application/vnd.hhe.lesson-player" to arrayOf("les"),
        "application/vnd.hp-hpgl" to arrayOf("hpgl"),
        "application/vnd.hp-hpid" to arrayOf("hpid"),
        "application/vnd.hp-hps" to arrayOf("hps"),
        "application/vnd.hp-jlyt" to arrayOf("jlt"),
        "application/vnd.hp-pcl" to arrayOf("pcl"),
        "application/vnd.hp-pclxl" to arrayOf("pclxl"),
        "application/vnd.hydrostatix.sof-data" to arrayOf("sfd-hdstx"),
        "application/vnd.hzn-3d-crossword" to arrayOf("x3d"),
        "application/vnd.ibm.minipay" to arrayOf("mpy"),
        "application/vnd.ibm.modcap" to arrayOf("afp", "listafp", "list3820"),
        "application/vnd.ibm.rights-management" to arrayOf("irm"),
        "application/vnd.ibm.secure-container" to arrayOf("sc"),
        "application/vnd.iccprofile" to arrayOf("icc", "icm"),
        "application/vnd.igloader" to arrayOf("igl"),
        "application/vnd.immervision-ivp" to arrayOf("ivp"),
        "application/vnd.immervision-ivu" to arrayOf("ivu"),
        "application/vnd.intercon.formnet" to arrayOf("xpw", "xpx"),
        "application/vnd.intu.qbo" to arrayOf("qbo"),
        "application/vnd.intu.qfx" to arrayOf("qfx"),
        "application/vnd.iptc.g2.newsmessage+xml" to arrayOf("nar"),
        "application/vnd.ipunplugged.rcprofile" to arrayOf("rcprofile"),
        "application/vnd.irepository.package+xml" to arrayOf("irp"),
        "application/vnd.is-xpr" to arrayOf("xpr"),
        "application/vnd.jam" to arrayOf("jam"),
        "application/vnd.jcp.javame.midlet-rms" to arrayOf("rms"),
        "application/vnd.jisp" to arrayOf("jisp"),
        "application/vnd.joost.joda-archive" to arrayOf("joda"),
        "application/vnd.kahootz" to arrayOf("ktz", "ktr"),
        "application/vnd.kde.karbon" to arrayOf("karbon"),
        "application/vnd.kde.kchart" to arrayOf("chrt"),
        "application/vnd.kde.kformula" to arrayOf("kfo"),
        "application/vnd.kde.kivio" to arrayOf("flw"),
        "application/vnd.kde.kontour" to arrayOf("kon"),
        "application/vnd.kde.kpresenter" to arrayOf("kpr", "kpt"),
        "application/vnd.kde.kspread" to arrayOf("ksp"),
        "application/vnd.kde.kword" to arrayOf("kwd", "kwt"),
        "application/vnd.kenameaapp" to arrayOf("htke"),
        "application/vnd.kidspiration" to arrayOf("kia"),
        "application/vnd.kinar" to arrayOf("kne", "knp"),
        "application/vnd.koan" to arrayOf("skp", "skd", "skt", "skm"),
        "application/vnd.kodak-descriptor" to arrayOf("sse"),
        "application/vnd.llamagraphics.life-balance.desktop" to arrayOf("lbd"),
        "application/vnd.llamagraphics.life-balance.exchange+xml" to arrayOf("lbe"),
        "application/vnd.lotus-1-2-3" to arrayOf("wk1", "wk2", "wk3", "wk4", "123"),
        "application/vnd.lotus-1-2-3;version=2" to arrayOf("wk1", "wk2"),
        "application/vnd.lotus-1-2-3;version=3" to arrayOf("wk3"),
        "application/vnd.lotus-1-2-3;version=4" to arrayOf("wk4"),
        "application/vnd.lotus-1-2-3;version=97+9.x" to arrayOf("123"),
        "application/vnd.lotus-approach" to arrayOf("apr"),
        "application/vnd.lotus-freelance" to arrayOf("pre"),
        "application/vnd.lotus-notes" to arrayOf("nsf"),
        "application/vnd.lotus-organizer" to arrayOf("org"),
        "application/vnd.lotus-wordpro" to arrayOf("lwp"),
        "application/vnd.macports.portpkg" to arrayOf("portpkg"),
        "application/vnd.mcd" to arrayOf("mcd"),
        "application/vnd.medcalcdata" to arrayOf("mc1"),
        "application/vnd.mediastation.cdkey" to arrayOf("cdkey"),
        "application/vnd.mfer" to arrayOf("mwf"),
        "application/vnd.mfmp" to arrayOf("mfm"),
        "application/vnd.micrografx.flo" to arrayOf("flo"),
        "application/vnd.micrografx.igx" to arrayOf("igx"),
        "application/vnd.mif" to arrayOf("mif"),
        "application/vnd.mindjet.mindmanager" to arrayOf("mmp", "mmap", "mmpt", "mmat", "mmmp", "mmas"),
        "application/vnd.mobius.daf" to arrayOf("daf"),
        "application/vnd.mobius.dis" to arrayOf("dis"),
        "application/vnd.mobius.mbk" to arrayOf("mbk"),
        "application/vnd.mobius.mqy" to arrayOf("mqy"),
        "application/vnd.mobius.msl" to arrayOf("msl"),
        "application/vnd.mobius.plc" to arrayOf("plc"),
        "application/vnd.mobius.txf" to arrayOf("txf"),
        "application/vnd.mophun.application" to arrayOf("mpn"),
        "application/vnd.mophun.certificate" to arrayOf("mpc"),
        "application/vnd.mozilla.xul+xml" to arrayOf("xul"),
        "application/vnd.ms-artgalry" to arrayOf("cil"),
        "application/vnd.ms-cab-compressed" to arrayOf("cab"),
        "application/vnd.ms-excel" to arrayOf("xls", "xlm", "xla", "xlc", "xlt", "xlw", "xll", "xld"),
        "application/vnd.ms-excel.addin.macroenabled.12" to arrayOf("xlam"),
        "application/vnd.ms-excel.sheet.macroenabled.12" to arrayOf("xlsm"),
        "application/vnd.ms-excel.sheet.binary.macroenabled.12" to arrayOf("xlsb"),
        "application/vnd.ms-fontobject" to arrayOf("eot"),
        "application/vnd.ms-htmlhelp" to arrayOf("chm"),
        "application/vnd.ms-ims" to arrayOf("ims"),
        "application/vnd.ms-lrm" to arrayOf("lrm"),
        "application/vnd.ms-outlook" to arrayOf("msg"),
        "application/vnd.ms-outlook-pst" to arrayOf("pst", "ost"),
        "application/vnd.ms-pki.seccat" to arrayOf("cat"),
        "application/vnd.ms-pki.stl" to arrayOf("stl"),
        "application/vnd.ms-powerpoint" to arrayOf("ppt", "ppz", "pps", "pot", "ppa"),
        "application/vnd.ms-powerpoint.addin.macroenabled.12" to arrayOf("ppam"),
        "application/vnd.ms-powerpoint.presentation.macroenabled.12" to arrayOf("pptm"),
        "application/vnd.ms-powerpoint.slide.macroenabled.12" to arrayOf("sldm"),
        "application/vnd.ms-powerpoint.slideshow.macroenabled.12" to arrayOf("ppsm"),
        "application/vnd.ms-powerpoint.template.macroenabled.12" to arrayOf("potm"),
        "application/vnd.ms-project" to arrayOf("mpp", "mpt"),
        "application/x-project" to arrayOf("mpx"),
        "application/vnd.ms-word.document.macroenabled.12" to arrayOf("docm"),
        "application/vnd.ms-word.template.macroenabled.12" to arrayOf("dotm"),
        "application/vnd.ms-works" to arrayOf("wps", "wks", "wcm", "wdb"),
        "application/vnd.ms-wpl" to arrayOf("wpl"),
        "application/vnd.ms-xpsdocument" to arrayOf("xps", "oxps"),
        "application/vnd.msa-disk-image" to arrayOf("msa"),
        "application/vnd.mseq" to arrayOf("mseq"),
        "application/vnd.musician" to arrayOf("mus"),
        "application/vnd.muvee.style" to arrayOf("msty"),
        "application/vnd.neurolanguage.nlu" to arrayOf("nlu"),
        "application/vnd.noblenet-directory" to arrayOf("nnd"),
        "application/vnd.noblenet-sealer" to arrayOf("nns"),
        "application/vnd.noblenet-web" to arrayOf("nnw"),
        "application/vnd.nokia.n-gage.data" to arrayOf("ngdat"),
        "application/vnd.nokia.n-gage.symbian.install" to arrayOf("n-gage"),
        "application/vnd.nokia.radio-preset" to arrayOf("rpst"),
        "application/vnd.nokia.radio-presets" to arrayOf("rpss"),
        "application/vnd.novadigm.edm" to arrayOf("edm"),
        "application/vnd.novadigm.edx" to arrayOf("edx"),
        "application/vnd.novadigm.ext" to arrayOf("ext"),
        "application/vnd.oasis.opendocument.chart" to arrayOf("odc"),
        "application/vnd.oasis.opendocument.chart-template" to arrayOf("otc"),
        "application/vnd.oasis.opendocument.base" to arrayOf("odb"),
        "application/vnd.oasis.opendocument.formula" to arrayOf("odf"),
        "application/vnd.oasis.opendocument.formula-template" to arrayOf("odft"),
        "application/vnd.oasis.opendocument.graphics" to arrayOf("odg"),
        "application/vnd.oasis.opendocument.graphics-template" to arrayOf("otg"),
        "application/vnd.oasis.opendocument.image" to arrayOf("odi"),
        "application/vnd.oasis.opendocument.image-template" to arrayOf("oti"),
        "application/vnd.oasis.opendocument.presentation" to arrayOf("odp"),
        "application/vnd.oasis.opendocument.presentation-template" to arrayOf("otp"),
        "application/vnd.oasis.opendocument.spreadsheet" to arrayOf("ods"),
        "application/vnd.oasis.opendocument.spreadsheet-template" to arrayOf("ots"),
        "application/vnd.oasis.opendocument.text" to arrayOf("odt"),
        "application/vnd.oasis.opendocument.flat.text" to arrayOf("fodt"),
        "application/vnd.oasis.opendocument.flat.presentation" to arrayOf("fodp"),
        "application/vnd.oasis.opendocument.flat.spreadsheet" to arrayOf("fods"),
        "application/vnd.oasis.opendocument.text-master" to arrayOf("otm"),
        "application/vnd.oasis.opendocument.text-template" to arrayOf("ott"),
        "application/vnd.oasis.opendocument.text-web" to arrayOf("oth"),
        "application/vnd.olpc-sugar" to arrayOf("xo"),
        "application/vnd.oma.dd2+xml" to arrayOf("dd2"),
        "application/vnd.openofficeorg.extension" to arrayOf("oxt"),
        "application/vnd.openofficeorg.autotext" to arrayOf("bau"),
        "application/vnd.openxmlformats-officedocument.presentationml.presentation" to arrayOf("pptx", "thmx"),
        "application/vnd.openxmlformats-officedocument.presentationml.slide" to arrayOf("sldx"),
        "application/vnd.openxmlformats-officedocument.presentationml.template" to arrayOf("potx"),
        "application/vnd.openxmlformats-officedocument.presentationml.slideshow" to arrayOf("ppsx"),
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" to arrayOf("xlsx"),
        "application/vnd.openxmlformats-officedocument.spreadsheetml.template" to arrayOf("xltx"),
        "application/vnd.ms-excel.template.macroenabled.12" to arrayOf("xltm"),
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document" to arrayOf("docx"),
        "application/vnd.openxmlformats-officedocument.wordprocessingml.template" to arrayOf("dotx"),
        "application/vnd.osgi.dp" to arrayOf("dp"),
        "application/vnd.palm" to arrayOf("pqa", "oprc"),
        "application/vnd.pg.format" to arrayOf("str"),
        "application/vnd.pg.osasli" to arrayOf("ei6"),
        "application/vnd.picsel" to arrayOf("efif"),
        "application/vnd.pocketlearn" to arrayOf("plf"),
        "application/vnd.powerbuilder6" to arrayOf("pbd"),
        "application/vnd.previewsystems.box" to arrayOf("box"),
        "application/vnd.proteus.magazine" to arrayOf("mgz"),
        "application/vnd.publishare-delta-tree" to arrayOf("qps"),
        "application/vnd.pvi.ptid1" to arrayOf("ptid"),
        "application/vnd.quark.quarkxpress" to arrayOf("qxd", "qxt", "qwd", "qwt", "qxl", "qxb"),
        "application/vnd.recordare.musicxml" to arrayOf("mxl"),
        "application/vnd.recordare.musicxml+xml" to arrayOf("musicxml"),
        "application/vnd.rim.cod" to arrayOf("cod"),
        "application/vnd.rn-realmedia" to arrayOf("rm"),
        "application/vnd.route66.link66+xml" to arrayOf("link66"),
        "application/vnd.seemail" to arrayOf("see"),
        "application/vnd.sema" to arrayOf("sema"),
        "application/vnd.semd" to arrayOf("semd"),
        "application/vnd.semf" to arrayOf("semf"),
        "application/vnd.shana.informed.formdata" to arrayOf("ifm"),
        "application/vnd.shana.informed.formtemplate" to arrayOf("itp"),
        "application/vnd.shana.informed.interchange" to arrayOf("iif"),
        "application/vnd.shana.informed.package" to arrayOf("ipk"),
        "application/vnd.simtech-mindmapper" to arrayOf("twd", "twds"),
        "application/vnd.smaf" to arrayOf("mmf"),
        "application/vnd.smart.teacher" to arrayOf("teacher"),
        "application/vnd.solent.sdkm+xml" to arrayOf("sdkm", "sdkd"),
        "application/vnd.spotfire.dxp" to arrayOf("dxp"),
        "application/vnd.spotfire.sfs" to arrayOf("sfs"),
        "application/vnd.stardivision.calc" to arrayOf("sdc"),
        "application/vnd.stardivision.draw" to arrayOf("sda"),
        "application/vnd.stardivision.impress" to arrayOf("sdd"),
        "application/vnd.stardivision.math" to arrayOf("smf"),
        "application/vnd.stardivision.writer" to arrayOf("sdw"),
        "application/x-staroffice-template" to arrayOf("vor"),
        "application/x-subrip" to arrayOf("srt"),
        "application/vnd.sun.xml.writer" to arrayOf("sxw"),
        "application/vnd.sun.xml.writer.template" to arrayOf("stw"),
        "application/vnd.sun.xml.calc" to arrayOf("sxc"),
        "application/vnd.sun.xml.draw" to arrayOf("sxd"),
        "application/vnd.sun.xml.impress" to arrayOf("sxi"),
        "application/vnd.stardivision.writer-global" to arrayOf("sgl"),
        "application/vnd.sun.xml.calc" to arrayOf("sxc"),
        "application/vnd.sun.xml.calc.template" to arrayOf("stc"),
        "application/vnd.sun.xml.draw" to arrayOf("sxd"),
        "application/vnd.sun.xml.draw.template" to arrayOf("std"),
        "application/vnd.sun.xml.impress" to arrayOf("sxi"),
        "application/vnd.sun.xml.impress.template" to arrayOf("sti"),
        "application/vnd.sun.xml.math" to arrayOf("sxm"),
        "application/vnd.sun.xml.writer" to arrayOf("sxw"),
        "application/vnd.sun.xml.writer.global" to arrayOf("sxg"),
        "application/vnd.sun.xml.writer.template" to arrayOf("stw"),
        "application/vnd.sus-calendar" to arrayOf("sus", "susp"),
        "application/vnd.svd" to arrayOf("svd"),
        "application/vnd.symbian.install" to arrayOf("sis", "sisx"),
        "application/vnd.syncml+xml" to arrayOf("xsm"),
        "application/vnd.syncml.dm+wbxml" to arrayOf("bdm"),
        "application/vnd.syncml.dm+xml" to arrayOf("xdm"),
        "application/vnd.tao.intent-module-archive" to arrayOf("tao"),
        "application/vnd.tcpdump.pcap" to arrayOf("pcap", "cap", "dmp"),
        "application/vnd.tcpdump.pcapng" to arrayOf("pcapng"),
        "application/vnd.tmobile-livetv" to arrayOf("tmo"),
        "application/x-tmx" to arrayOf("tmx"),
        "application/vnd.trid.tpt" to arrayOf("tpt"),
        "application/vnd.triscape.mxs" to arrayOf("mxs"),
        "application/vnd.trueapp" to arrayOf("tra"),
        "application/vnd.ufdl" to arrayOf("ufd", "ufdl"),
        "application/ttml+xml" to arrayOf("ttml"),
        "application/vnd.uiq.theme" to arrayOf("utz"),
        "application/vnd.umajin" to arrayOf("umj"),
        "application/vnd.unity" to arrayOf("unityweb"),
        "application/vnd.uoml+xml" to arrayOf("uoml"),
        "application/vnd.vcx" to arrayOf("vcx"),
        "application/vnd.visio" to arrayOf("vsd", "vst", "vss", "vsw"),
        "application/vnd.ms-visio.drawing" to arrayOf("vsdx"),
        "application/vnd.ms-visio.template" to arrayOf("vstx"),
        "application/vnd.ms-visio.stencil" to arrayOf("vssx"),
        "application/vnd.ms-visio.drawing.macroEnabled.12" to arrayOf("vsdm"),
        "application/vnd.ms-visio.template.macroEnabled.12" to arrayOf("vstm"),
        "application/vnd.ms-visio.stencil.macroEnabled.12" to arrayOf("vssm"),
        "application/vnd.visionary" to arrayOf("vis"),
        "application/vnd.vsf" to arrayOf("vsf"),
        "application/vnd.wap.wbxml" to arrayOf("wbxml"),
        "application/vnd.wap.wmlc" to arrayOf("wmlc"),
        "application/vnd.wap.wmlscriptc" to arrayOf("wmlsc"),
        "application/vnd.webturbo" to arrayOf("wtb"),
        "application/vnd.wordperfect" to arrayOf("wpd", "wp", "wp5", "wp6", "w60", "wp61", "wpt"),
        "application/vnd.wqd" to arrayOf("wqd"),
        "application/vnd.wt.stf" to arrayOf("stf"),
        "application/vnd.xara" to arrayOf("xar"),
        "application/vnd.xfdl" to arrayOf("xfdl"),
        "application/vnd.yamaha.hv-dic" to arrayOf("hvd"),
        "application/vnd.yamaha.hv-script" to arrayOf("hvs"),
        "application/vnd.yamaha.hv-voice" to arrayOf("hvp"),
        "application/vnd.yamaha.openscoreformat" to arrayOf("osf"),
        "application/vnd.yamaha.openscoreformat.osfpvg+xml" to arrayOf("osfpvg"),
        "application/vnd.yamaha.smaf-audio" to arrayOf("saf"),
        "application/vnd.yamaha.smaf-phrase" to arrayOf("spf"),
        "application/vnd.yellowriver-custom-menu" to arrayOf("cmp"),
        "application/vnd.zul" to arrayOf("zir", "zirz"),
        "application/vnd.zzazz.deck+xml" to arrayOf("zaz"),
        "application/voicexml+xml" to arrayOf("vxml"),
        "application/warc" to arrayOf("warc"),
        "application/wasm" to arrayOf("wasm"),
        "application/winhlp" to arrayOf("hlp"),
        "application/wsdl+xml" to arrayOf("wsdl"),
        "application/wspolicy+xml" to arrayOf("wspolicy"),
        "image/x-tga" to arrayOf("tga", "icb", "vda"),
        "application/x-abiword" to arrayOf("abw"),
        "application/x-ace-compressed" to arrayOf("ace"),
        "application/x-axcrypt" to arrayOf("axx"),
        "application/x-adobe-indesign" to arrayOf("indd"),
        "application/vnd.isac.fcs" to arrayOf("fcs"),
        "application/vnd.adobe.indesign-idml-package" to arrayOf("idml"),
        "application/x-adobe-indesign-interchange" to arrayOf("inx"),
        "application/x-apple-diskimage" to arrayOf("dmg"),
        "application/x-appleworks" to arrayOf("cwk"),
        "application/x-archive" to arrayOf("ar", "a"),
        "application/x-arj" to arrayOf("arj"),
        "application/x-asprs" to arrayOf("las", "laz"),
        "application/x-authorware-bin" to arrayOf("aab", "x32", "u32", "vox"),
        "application/x-authorware-map" to arrayOf("aam"),
        "application/x-authorware-seg" to arrayOf("aas"),
        "application/x-bcpio" to arrayOf("bcpio"),
        "application/x-bibtex-text-file" to arrayOf("bib", "bibtex"),
        "application/x-bittorrent" to arrayOf("torrent"),
        "application/x-gtar" to arrayOf("gtar"),
        "application/x-amiga-disk-format" to arrayOf("adf"),
        "application/x-brotli" to arrayOf("br", "brotli"),
        "application/x-bzip" to arrayOf("bz", "tbz"),
        "application/x-bzip2" to arrayOf("bz2", "tbz2", "boz"),
        "application/x-cdlink" to arrayOf("vcd"),
        "application/x-chat" to arrayOf("chat"),
        "application/x-chess-pgn" to arrayOf("pgn"),
        "application/x-chrome-package" to arrayOf("crx"),
        "application/x-compress" to arrayOf("z"),
        "application/x-corelpresentations" to arrayOf("shw"),
        "application/x-cpio" to arrayOf("cpio"),
        "application/x-csh" to arrayOf("csh", "tcsh"),
        "application/x-debian-package" to arrayOf("deb", "udeb"),
        "application/x-dex" to arrayOf("dex"),
        "application/x-director" to arrayOf("dir", "dcr", "dxr", "cst", "cct", "cxt", "w3d", "fgd", "swa"),
        "application/x-doom" to arrayOf("wad"),
        "application/x-dtbncx+xml" to arrayOf("ncx"),
        "application/x-dtbook+xml" to arrayOf("dtb"),
        "application/x-dtbresource+xml" to arrayOf("res"),
        "application/x-dvi" to arrayOf("dvi"),
        "application/x-elc" to arrayOf("elc"),
        "message/x-emlx" to arrayOf("emlx"),
        "application/x-endnote-refer" to arrayOf("enw", "enr"),
        "application/x-endnote-style" to arrayOf("ens"),
        "application/x-killustrator" to arrayOf("kil"),
        "application/x-dosexec" to arrayOf("exe"),
        "application/x-erdas-hfa" to arrayOf("hfa"),
        "application/x-filemaker" to arrayOf("fp7"),
        "application/x-font-bdf" to arrayOf("bdf"),
        "application/x-font-ghostscript" to arrayOf("gsf"),
        "application/x-font-linux-psf" to arrayOf("psf"),
        "application/x-font-otf" to arrayOf("otf"),
        "application/x-font-pcf" to arrayOf("pcf"),
        "application/x-font-snf" to arrayOf("snf"),
        "application/x-font-ttf" to arrayOf("ttf", "ttc"),
        "application/x-font-type1" to arrayOf("pfa", "pfb"),
        "application/x-font-adobe-metric" to arrayOf("afm", "acfm", "amfm"),
        "application/x-font-printer-metric" to arrayOf("pfm"),
        "application/x-futuresplash" to arrayOf("spl"),
        "application/x-gnucash" to arrayOf("gnucash"),
        "application/x-gnumeric" to arrayOf("gnumeric"),
        "application/x-grib" to arrayOf("grb", "grb1", "grb2"),
        "application/gzip" to arrayOf("gz", "tgz", "gz"),
        "application/zstd" to arrayOf("zst"),
        "application/x-esri-layer" to arrayOf("lyr"),
        "application/x-hdf" to arrayOf("hdf", "he5", "h5"),
        "application/x-ibooks+zip" to arrayOf("ibooks"),
        "application/x-internet-archive" to arrayOf("arc"),
        "application/x-isatab-investigation" to arrayOf("*.txt"),
        "application/x-isatab" to arrayOf("*.txt"),
        "application/x-isatab-assay" to arrayOf("*.txt"),
        "application/x-iso9660-image" to arrayOf("iso"),
        "application/x-itunes-ipa" to arrayOf("ipa"),
        "application/x-java-jnlp-file" to arrayOf("jnlp"),
        "application/x-java-pack200" to arrayOf("pack"),
        "application/x-jeol-jdf" to arrayOf("jdf"),
        "application/x-latex" to arrayOf("latex"),
        "application/x-lz4" to arrayOf("lz4"),
        "application/x-lzip" to arrayOf("lz"),
        "application/x-lzma" to arrayOf("lzma"),
        "application/x-memgraph" to arrayOf("memgraph"),
        "application/x-mobipocket-ebook" to arrayOf("prc", "mobi"),
        "application/x-ms-application" to arrayOf("application"),
        "application/x-ms-wmd" to arrayOf("wmd"),
        "application/x-ms-wmz" to arrayOf("wmz"),
        "application/x-ms-xbap" to arrayOf("xbap"),
        "application/x-msaccess" to arrayOf("mdb"),
        "application/x-msbinder" to arrayOf("obd"),
        "application/x-mscardfile" to arrayOf("crd"),
        "application/x-msclip" to arrayOf("clp"),
        "application/x-msdownload" to arrayOf("dll", "com"),
        "application/x-ms-installer" to arrayOf("msi", "msp", "mst"),
        "application/x-msmediaview" to arrayOf("mvb", "m13", "m14"),
        "application/x-msmoney" to arrayOf("mny"),
        "application/x-mspublisher" to arrayOf("pub"),
        "application/x-msschedule" to arrayOf("scd"),
        "application/x-msterminal" to arrayOf("trm"),
        "application/x-mswrite" to arrayOf("wri"),
        "application/x-mysql-misam-compressed-index" to arrayOf("MYI"),
        "application/x-mysql-misam-data" to arrayOf("MYD"),
        "application/x-nesrom" to arrayOf("nes"),
        "application/x-netcdf" to arrayOf("nc", "cdf"),
        "application/x-parquet" to arrayOf("parquet"),
        "application/x-pkcs12" to arrayOf("p12", "pfx"),
        "application/x-pkcs7-certificates" to arrayOf("p7b", "spc"),
        "application/x-pkcs7-certreqresp" to arrayOf("p7r"),
        "application/x-prt" to arrayOf("prt"),
        "application/x-quattro-pro" to arrayOf("wq1", "wq2", "wkq", "qpw", "wb1", "wb2", "wb3"),
        "application/x-quattro-pro;version=1-4" to arrayOf("wq1", "wkq"),
        "application/x-quattro-pro;version=5" to arrayOf("wq2", "wkq"),
        "application/x-quattro-pro;version=1+5" to arrayOf("wb1"),
        "application/x-quattro-pro;version=6" to arrayOf("wb2"),
        "application/xquery" to arrayOf("xq", "xquery"),
        "application/x-rar-compressed" to arrayOf("rar"),
        "application/x-roxio-toast" to arrayOf("toast"),
        "application/x-rpm" to arrayOf("rpm"),
        "application/x-sas" to arrayOf("sas"),
        "application/x-sas-program-data" to arrayOf("ss7", "sas7bpgm"),
        "application/x-sas-audit" to arrayOf("st7", "sas7baud"),
        "application/x-sas-data-v6" to arrayOf("sd2"),
        "application/x-sas-data" to arrayOf("sd7", "sas7bdat"),
        "application/x-sas-view" to arrayOf("sv7", "sas7bvew"),
        "application/x-sas-data-index" to arrayOf("si7", "sas7bndx"),
        "application/x-sas-catalog" to arrayOf("sc7", "sas7bcat"),
        "application/x-sas-access" to arrayOf("sa7", "sas7bacs"),
        "application/x-sas-fdb" to arrayOf("sf7", "sas7bfdb"),
        "application/x-sas-mddb" to arrayOf("sm7", "sas7bmdb"),
        "application/x-sas-dmdb" to arrayOf("s7m", "sas7bdmd"),
        "application/x-sas-itemstor" to arrayOf("sr7", "sas7bitm"),
        "application/x-sas-utility" to arrayOf("su7", "sas7butl"),
        "application/x-sas-putility" to arrayOf("sp7", "sas7bput"),
        "application/x-sas-transport" to arrayOf("stx"),
        "application/x-sas-backup" to arrayOf("sas7bbak"),
        "application/x-sas-xport" to arrayOf("xpt", "xport"),
        "application/x-spss-sav" to arrayOf("sav"),
        "application/x-sh" to arrayOf("sh", "bash"),
        "application/x-shar" to arrayOf("shar"),
        "application/x-shapefile" to arrayOf("shp"),
        "application/x-shockwave-flash" to arrayOf("swf"),
        "application/x-sibelius" to arrayOf("sib"),
        "application/x-silverlight-app" to arrayOf("xap"),
        "application/x-snappy-framed" to arrayOf("sz"),
        "application/x-sfdu" to arrayOf("sfdu"),
        "application/x-spectrum-tzx" to arrayOf("tzx"),
        "application/x-stata-do" to arrayOf("do"),
        "application/x-stata-dta" to arrayOf("dta"),
        "application/x-stuffit" to arrayOf("sit"),
        "application/x-stuffitx" to arrayOf("sitx"),
        "application/x-sv4cpio" to arrayOf("sv4cpio"),
        "application/x-sv4crc" to arrayOf("sv4crc"),
        "application/x-tar" to arrayOf("tar"),
        "application/x-tex" to arrayOf("tex"),
        "application/x-tex-tfm" to arrayOf("tfm"),
        "application/x-texinfo" to arrayOf("texinfo", "texi"),
        "application/x-tika-msworks-spreadsheet" to arrayOf("xlr"),
        "application/x-uc2-compressed" to arrayOf("uc2"),
        "application/x-ustar" to arrayOf("ustar"),
        "application/x-vmdk" to arrayOf("vmdk"),
        "application/x-wais-source" to arrayOf("src"),
        "application/x-webarchive" to arrayOf("webarchive"),
        "application/x-x509-cert" to arrayOf("crt"),
        "application/x-x509-cert;format=pem" to arrayOf("pem"),
        "application/x-x509-cert;format=der" to arrayOf("der"),
        "application/x-xfig" to arrayOf("fig"),
        "application/x-xpinstall" to arrayOf("xpi"),
        "application/x-xmind" to arrayOf("xmind"),
        "application/x-xz" to arrayOf("xz"),
        "application/x-zoo" to arrayOf("zoo"),
        "application/xenc+xml" to arrayOf("xenc"),
        "application/xhtml+xml" to arrayOf("xhtml", "xhtml2", "xht"),
        "application/xml" to arrayOf("xml", "xsl", "xsd"),
        "application/xml-dtd" to arrayOf("dtd"),
        "application/xop+xml" to arrayOf("xop"),
        "application/xslfo+xml" to arrayOf("xslfo", "fo"),
        "application/xslt+xml" to arrayOf("xslt"),
        "application/xspf+xml" to arrayOf("xspf"),
        "application/xv+xml" to arrayOf("mxml", "xhvml", "xvml", "xvm"),
        "application/zip" to arrayOf("zip"),
        "application/x-7z-compressed" to arrayOf("7z"),
        "audio/ac3" to arrayOf("ac3"),
        "audio/adpcm" to arrayOf("adp"),
        "audio/amr" to arrayOf("amr"),
        "audio/basic" to arrayOf("au", "snd"),
        "audio/midi" to arrayOf("mid", "midi", "kar", "rmi"),
        "audio/mp4" to arrayOf("mp4a", "m4a", "m4b"),
        "audio/mpeg" to arrayOf("mpga", "mp2", "mp2a", "mp3", "m2a", "m3a"),
        "audio/ogg" to arrayOf("oga"),
        "audio/vorbis" to arrayOf("ogg"),
        "audio/x-psf" to arrayOf("psf1", "psflib", "minipsf", "minipsf1", "gslib", "minigsf"),
        "audio/x-sap" to arrayOf("sap"),
        "audio/opus" to arrayOf("opus"),
        "audio/speex" to arrayOf("spx"),
        "audio/vnd.adobe.soundbooth" to arrayOf("asnd"),
        "audio/vnd.digital-winds" to arrayOf("eol"),
        "audio/vnd.dts" to arrayOf("dts"),
        "audio/vnd.dts.hd" to arrayOf("dtshd"),
        "audio/vnd.lucent.voice" to arrayOf("lvp"),
        "audio/vnd.ms-playready.media.pya" to arrayOf("pya"),
        "audio/vnd.nuera.ecelp4800" to arrayOf("ecelp4800"),
        "audio/vnd.nuera.ecelp7470" to arrayOf("ecelp7470"),
        "audio/vnd.nuera.ecelp9600" to arrayOf("ecelp9600"),
        "audio/x-aac" to arrayOf("aac"),
        "audio/x-aiff" to arrayOf("aif", "aiff", "aifc"),
        "audio/x-caf" to arrayOf("caf"),
        "audio/x-flac" to arrayOf("flac"),
        "audio/x-mod" to arrayOf("mod"),
        "audio/x-mpegurl" to arrayOf("m3u"),
        "audio/x-ms-wax" to arrayOf("wax"),
        "audio/x-ms-wma" to arrayOf("wma"),
        "audio/x-pn-realaudio" to arrayOf("ram", "ra"),
        "audio/x-pn-realaudio-plugin" to arrayOf("rmp"),
        "audio/vnd.wave" to arrayOf("wav"),
        "chemical/x-cdx" to arrayOf("cdx"),
        "chemical/x-cif" to arrayOf("cif"),
        "chemical/x-cmdf" to arrayOf("cmdf"),
        "chemical/x-cml" to arrayOf("cml"),
        "chemical/x-csml" to arrayOf("csml"),
        "chemical/x-pdb" to arrayOf("pdb"),
        "chemical/x-xyz" to arrayOf("xyz"),
        "image/x-3ds" to arrayOf("3ds"),
        "image/aces" to arrayOf("exr"),
        "image/bmp" to arrayOf("bmp", "dib"),
        "image/x-bpg" to arrayOf("bpg"),
        "image/cgm" to arrayOf("cgm"),
        "image/x-dpx" to arrayOf("dpx"),
        "image/emf" to arrayOf("emf"),
        "image/x-emf-compressed" to arrayOf("emz"),
        "image/g3fax" to arrayOf("g3"),
        "image/gif" to arrayOf("gif"),
        "image/avif" to arrayOf("avif"),
        "image/heif" to arrayOf("heif"),
        "image/heic" to arrayOf("heic"),
        "image/icns" to arrayOf("icns"),
        "image/ief" to arrayOf("ief"),
        "image/jp2" to arrayOf("jp2"),
        "image/jpeg" to arrayOf("jpg", "jpeg", "jpe", "jif", "jfif", "jfi"),
        "image/jpm" to arrayOf("jpm", "jpgm"),
        "image/jpx" to arrayOf("jpf"),
        "image/nitf" to arrayOf("ntf", "nitf"),
        "image/png" to arrayOf("png"),
        "image/prs.btif" to arrayOf("btif"),
        "image/svg+xml" to arrayOf("svg", "svgz"),
        "image/tiff" to arrayOf("tiff", "tif"),
        "image/vnd.adobe.photoshop" to arrayOf("psd"),
        "image/vnd.adobe.premiere" to arrayOf("ppj"),
        "image/vnd.dgn" to arrayOf("dgn", "dgnlib", "cel"),
        "image/vnd.djvu" to arrayOf("djvu", "djv"),
        "image/vnd.dwg" to arrayOf("dwg"),
        "image/vnd.dxb" to arrayOf("dxb"),
        "image/vnd.dxf" to arrayOf("dxf"),
        "image/vnd.fastbidsheet" to arrayOf("fbs"),
        "image/vnd.fpx" to arrayOf("fpx"),
        "image/vnd.fst" to arrayOf("fst"),
        "image/vnd.fujixerox.edmics-mmr" to arrayOf("mmr"),
        "image/vnd.fujixerox.edmics-rlc" to arrayOf("rlc"),
        "image/vnd.microsoft.icon" to arrayOf("ico"),
        "image/vnd.ms-modi" to arrayOf("mdi"),
        "image/vnd.net-fpx" to arrayOf("npx"),
        "image/vnd.wap.wbmp" to arrayOf("wbmp"),
        "image/vnd.zbrush.dcx" to arrayOf("dcx"),
        "image/vnd.zbrush.pcx" to arrayOf("pcx"),
        "image/webp" to arrayOf("webp"),
        "image/heic" to arrayOf("heic"),
        "image/heif" to arrayOf("heif"),
        "image/wmf" to arrayOf("wmf"),
        "image/vnd.xiff" to arrayOf("xif"),
        "image/x-cmu-raster" to arrayOf("ras"),
        "image/x-cmx" to arrayOf("cmx"),
        "image/x-freehand" to arrayOf(
            "fh",
            "fhc",
            "fh4",
            "fh40",
            "fh5",
            "fh50",
            "fh7",
            "fh8",
            "fh9",
            "fh10",
            "fh11",
            "fh12",
            "ft7",
            "ft8",
            "ft9",
            "ft10",
            "ft11",
            "ft12"
        ),
        "image/x-jbig2" to arrayOf("jb2", "jbig2"),
        "image/x-jp2-codestream" to arrayOf("j2c"),
        "image/jxl" to arrayOf("jxl"),
        "image/x-pict" to arrayOf("pic", "pct", "pict"),
        "image/x-portable-anymap" to arrayOf("pnm"),
        "image/x-portable-bitmap" to arrayOf("pbm"),
        "image/x-portable-graymap" to arrayOf("pgm"),
        "image/x-portable-pixmap" to arrayOf("ppm"),
        "image/x-raw-adobe" to arrayOf("dng"),
        "image/x-raw-hasselblad" to arrayOf("3fr"),
        "image/x-raw-fuji" to arrayOf("raf"),
        "image/x-raw-canon" to arrayOf("crw"),
        "image/x-canon-cr2" to arrayOf("cr2"),
        "image/x-canon-cr3" to arrayOf("cr3"),
        "image/x-raw-kodak" to arrayOf("k25", "kdc", "dcs", "drf"),
        "image/x-raw-minolta" to arrayOf("mrw"),
        "image/x-raw-nikon" to arrayOf("nef", "nrw"),
        "image/x-raw-olympus" to arrayOf("orf"),
        "image/x-raw-pentax" to arrayOf("ptx", "pef"),
        "image/x-raw-sony" to arrayOf("arw", "srf", "sr2"),
        "image/x-raw-sigma" to arrayOf("x3f"),
        "image/x-raw-epson" to arrayOf("erf"),
        "image/x-raw-mamiya" to arrayOf("mef"),
        "image/x-raw-leaf" to arrayOf("mos"),
        "image/x-raw-panasonic" to arrayOf("raw", "rw2"),
        "image/x-raw-phaseone" to arrayOf("iiq"),
        "image/x-raw-red" to arrayOf("r3d"),
        "image/x-raw-imacon" to arrayOf("fff"),
        "image/x-raw-logitech" to arrayOf("pxn"),
        "image/x-raw-casio" to arrayOf("bay"),
        "image/x-raw-rawzor" to arrayOf("rwz"),
        "image/x-rgb" to arrayOf("rgb"),
        "image/x-xbitmap" to arrayOf("xbm"),
        "image/x-xcf" to arrayOf("xcf"),
        "image/x-xpixmap" to arrayOf("xpm"),
        "image/x-xwindowdump" to arrayOf("xwd"),
        "message/rfc822" to arrayOf("eml", "mime"),
        "multipart/related" to arrayOf("mht", "mhtml"),
        "model/e57" to arrayOf("e57"),
        "model/iges" to arrayOf("igs", "iges"),
        "model/mesh" to arrayOf("msh", "mesh", "silo"),
        "model/vnd.dwf" to arrayOf("dwf"),
        "model/vnd.dwfx+xps" to arrayOf("dwfx"),
        "model/vnd.gdl" to arrayOf("gdl"),
        "model/vnd.gtw" to arrayOf("gtw"),
        "model/vnd.mts" to arrayOf("mts"),
        "model/vnd.vtu" to arrayOf("vtu"),
        "model/vrml" to arrayOf("wrl", "vrml"),
        "application/dif+xml" to arrayOf("dif"),
        "text/x-actionscript" to arrayOf("as"),
        "text/x-ada" to arrayOf("ada", "adb", "ads"),
        "text/x-applescript" to arrayOf("applescript"),
        "text/asp" to arrayOf("asp"),
        "text/aspdotnet" to arrayOf("aspx"),
        "text/x-aspectj" to arrayOf("aj"),
        "text/x-assembly" to arrayOf("s", "S", "asm"),
        "text/calendar" to arrayOf("ics", "ifb"),
        "text/x-config" to arrayOf("config", "conf", "cfg", "xconf"),
        "text/css" to arrayOf("css"),
        "text/csv" to arrayOf("csv"),
        "text/html" to arrayOf("html", "htm"),
        "text/x-makefile" to arrayOf("kefile", "UMakefile"),
        "text/plain" to arrayOf(
            "txt",
            "text",
            "def",
            "list",
            "in",
            "STALL",
            "YS",
            "CENSE",
            "TICE",
            "ADME",
            "s-linkmap",
            "s-menulinks",
            "aart",
            "ac",
            "am",
            "apt",
            "bsh",
            "classpath",
            "cnd",
            "cwiki",
            "data",
            "dcl",
            "dsp",
            "dsw",
            "egrm",
            "ent",
            "ft",
            "fn",
            "fv",
            "grm",
            "g",
            "taccess",
            "handlers",
            "htc",
            "ihtml",
            "jmx",
            "junit",
            "jx",
            "manifest",
            "m4",
            "mf",
            "MF",
            "meta",
            "mdo",
            "n3",
            "pen",
            "pod",
            "pom",
            "project",
            "rng",
            "rnx",
            "roles",
            "schemas",
            "tld",
            "types",
            "vm",
            "vsl",
            "wsdd",
            "xargs",
            "xcat",
            "xegrm",
            "xgrm",
            "xlex",
            "xlog",
            "xmap",
            "xroles",
            "xsamples",
            "xsp",
            "xtest",
            "xweb",
            "xwelcome"
        ),
        "text/prs.lines.tag" to arrayOf("dsc"),
        "text/richtext" to arrayOf("rtx"),
        "text/sgml" to arrayOf("sgml", "sgm"),
        "text/tab-separated-values" to arrayOf("tsv"),
        "text/troff" to arrayOf("t", "tr", "roff", "nroff", "man", "me", "ms"),
        "text/uri-list" to arrayOf("uri", "uris", "urls"),
        "text/vnd.curl" to arrayOf("curl"),
        "text/vnd.curl.dcurl" to arrayOf("dcurl"),
        "text/vnd.curl.scurl" to arrayOf("scurl"),
        "text/vnd.curl.mcurl" to arrayOf("mcurl"),
        "text/vnd.fly" to arrayOf("fly"),
        "text/vnd.fmi.flexstor" to arrayOf("flx"),
        "text/vnd.graphviz" to arrayOf("gv"),
        "text/vnd.in3d.3dml" to arrayOf("3dml"),
        "text/vnd.in3d.spot" to arrayOf("spot"),
        "text/vnd.iptc.anpa" to arrayOf("anpa"),
        "text/vnd.sun.j2me.app-descriptor" to arrayOf("jad"),
        "text/vnd.wap.wml" to arrayOf("wml"),
        "text/vnd.wap.wmlscript" to arrayOf("wmls"),
        "text/vtt" to arrayOf("vtt"),
        "text/x-awk" to arrayOf("awk"),
        "text/x-basic" to arrayOf("bas", "Bas", "BAS"),
        "text/x-c++hdr" to arrayOf("hpp", "hxx", "hh", "H", "h++", "hp", "HPP"),
        "text/x-c++src" to arrayOf("cpp", "cxx", "cc", "C", "c++", "CPP"),
        "text/x-cgi" to arrayOf("cgi"),
        "text/x-chdr" to arrayOf("h"),
        "text/x-clojure" to arrayOf("clj"),
        "text/x-coffeescript" to arrayOf("coffee"),
        "text/x-csrc" to arrayOf("c"),
        "text/x-csharp" to arrayOf("cs"),
        "text/x-cobol" to arrayOf("cbl", "Cbl", "CBL", "cob", "Cob", "COB"),
        "text/x-coldfusion" to arrayOf("cfm", "cfml", "cfc"),
        "text/x-common-lisp" to arrayOf("cl", "jl", "lisp", "lsp"),
        "text/x-diff" to arrayOf("diff", "patch"),
        "text/x-eiffel" to arrayOf("e"),
        "text/x-emacs-lisp" to arrayOf("el"),
        "text/x-erlang" to arrayOf("erl"),
        "text/x-expect" to arrayOf("exp"),
        "text/x-forth" to arrayOf("4th"),
        "text/x-fortran" to arrayOf("f", "F", "for", "f77", "f90"),
        "text/x-go" to arrayOf("go"),
        "text/x-groovy" to arrayOf("groovy"),
        "text/x-haskell" to arrayOf("hs", "lhs"),
        "text/x-idl" to arrayOf("idl"),
        "text/x-ini" to arrayOf("ini"),
        "text/x-java-source" to arrayOf("java"),
        "text/x-java-properties" to arrayOf("properties"),
        "text/x-jsp" to arrayOf("jsp"),
        "text/x-less" to arrayOf("less"),
        "text/x-lex" to arrayOf("l"),
        "text/x-log" to arrayOf("log"),
        "text/x-lua" to arrayOf("lua"),
        "text/x-ml" to arrayOf("ml"),
        "application/x-matlab-data" to arrayOf("mat"),
        "text/x-modula" to arrayOf("m3", "i3", "mg", "ig"),
        "text/x-objcsrc" to arrayOf("m"),
        "text/x-ocaml" to arrayOf("ocaml", "mli"),
        "text/x-pascal" to arrayOf("p", "pp", "pas", "PAS", "dpr"),
        "text/x-perl" to arrayOf("pl", "pm", "al", "perl"),
        "text/x-php" to arrayOf("php", "php3", "php4"),
        "text/x-prolog" to arrayOf("pro"),
        "text/x-python" to arrayOf("py"),
        "text/x-rst" to arrayOf("rest", "rst", "restx"),
        "text/x-rexx" to arrayOf("rexx"),
        "text/x-ruby" to arrayOf("rb"),
        "text/x-scala" to arrayOf("scala"),
        "text/x-scheme" to arrayOf("scm"),
        "text/x-sed" to arrayOf("sed"),
        "text/x-sql" to arrayOf("sql"),
        "text/x-setext" to arrayOf("etx"),
        "text/x-stsrc" to arrayOf("st"),
        "text/x-tcl" to arrayOf("itk", "tcl", "tk"),
        "text/x-uuencode" to arrayOf("uu"),
        "text/x-vbasic" to arrayOf("cls", "Cls", "CLS", "frm", "Frm", "FRM"),
        "text/x-vbdotnet" to arrayOf("vb"),
        "text/x-vbscript" to arrayOf("vbs"),
        "text/x-vcalendar" to arrayOf("vcs"),
        "text/x-vcard" to arrayOf("vcf"),
        "text/x-verilog" to arrayOf("v"),
        "text/x-vhdl" to arrayOf("vhd", "vhdl"),
        "text/x-web-markdown" to arrayOf("md", "mdtext", "mkd", "markdown"),
        "text/x-yacc" to arrayOf("y"),
        "text/x-yaml" to arrayOf("yaml", "yml"),
        "video/3gpp" to arrayOf("3gp"),
        "video/3gpp2" to arrayOf("3g2"),
        "video/h261" to arrayOf("h261"),
        "video/h263" to arrayOf("h263"),
        "video/h264" to arrayOf("h264"),
        "video/iso.segment" to arrayOf("m4s"),
        "video/jpeg" to arrayOf("jpgv"),
        "video/mj2" to arrayOf("mj2", "mjp2"),
        "video/mp4" to arrayOf("mp4", "mp4v", "mpg4"),
        "video/mpeg" to arrayOf("mpeg", "mpg", "mpe", "m1v", "m2v"),
        "video/ogg" to arrayOf("ogv"),
        "video/x-dirac" to arrayOf("drc"),
        "video/x-ogm" to arrayOf("ogm"),
        "video/quicktime" to arrayOf("qt", "mov"),
        "video/vnd.fvt" to arrayOf("fvt"),
        "video/vnd.mpegurl" to arrayOf("mxu", "m4u"),
        "video/vnd.ms-playready.media.pyv" to arrayOf("pyv"),
        "video/vnd.vivo" to arrayOf("viv"),
        "video/x-f4v" to arrayOf("f4v"),
        "video/x-flc" to arrayOf("flc"),
        "video/x-fli" to arrayOf("fli"),
        "video/x-flv" to arrayOf("flv"),
        "video/x-jng" to arrayOf("jng"),
        "video/x-m4v" to arrayOf("m4v"),
        "video/x-mng" to arrayOf("mng"),
        "video/x-ms-asf" to arrayOf("asf"),
        "application/x-ms-asx" to arrayOf("asx"),
        "video/x-ms-wm" to arrayOf("wm"),
        "video/x-ms-wmv" to arrayOf("wmv"),
        "video/x-ms-wmx" to arrayOf("wmx"),
        "video/x-ms-wvx" to arrayOf("wvx"),
        "video/x-msvideo" to arrayOf("avi"),
        "video/x-sgi-movie" to arrayOf("movie"),
        "video/x-matroska" to arrayOf("mkv"),
        "audio/x-matroska" to arrayOf("mka"),
        "video/webm" to arrayOf("webm"),
        "x-conference/x-cooltalk" to arrayOf("ice"),
        "application/x-fictionbook+xml" to arrayOf("fb2"),
        "text/x-asciidoc" to arrayOf("asciidoc", "adoc", "ad", "ad.txt", "adoc.txt"),
        "text/x-d" to arrayOf("d"),
        "text/x-haml" to arrayOf("haml"),
        "text/x-haxe" to arrayOf("hx"),
        "application/x-xliff+xml" to arrayOf("xlf", "xliff"),
        "application/x-xliff+zip" to arrayOf("xlz"),
        "text/x-rsrc" to arrayOf("r"),
    )

    val extensionToMimeType by lazy {
       Util.createReverseMap(mimeTypeToExtensions)
    }
}
