package fe.linksheet.util.mime

object KnownMimeTypes {
    val mimeTypeToExtensions = mapOf(
        "application/andrew-inset" to listOf("ez"),
        "application/applixware" to listOf("aw"),
        "text/iso19139+xml" to listOf("iso19139"),
        "application/atom+xml" to listOf("atom"),
        "application/atomcat+xml" to listOf("atomcat"),
        "application/atomsvc+xml" to listOf("atomsvc"),
        "application/x-bat" to listOf("bat", "cmd"),
        "application/bizagi-modeler" to listOf("bpm"),
        "application/cbor" to listOf("cbor"),
        "application/ccxml+xml" to listOf("ccxml"),
        "application/coreldraw" to listOf("cdr"),
        "application/cu-seeme" to listOf("cu"),
        "application/dash+xml" to listOf("mpd"),
        "application/davmount+xml" to listOf("davmount"),
        "application/x-dbf" to listOf("dbf", "dbase", "dbase3"),
        "application/dita+xml;format=map" to listOf("ditamap"),
        "application/dita+xml;format=topic" to listOf("dita"),
        "application/dita+xml;format=val" to listOf("ditaval"),
        "application/x-dvd-ifo" to listOf("ifo", "bup"),
        "application/ecmascript" to listOf("ecma"),
        "application/emma+xml" to listOf("emma"),
        "application/envi.hdr" to listOf("hdr"),
        "application/epub+zip" to listOf("epub"),
        "application/fits" to listOf("fits", "fit", "fts"),
        "application/font-tdpfr" to listOf("pfr"),
        "application/hyperstudio" to listOf("stk"),
        "application/illustrator" to listOf("ai"),
        "application/java-archive" to listOf("jar"),
        "application/vnd.android.package-archive" to listOf("apk"),
        "application/x-tika-java-enterprise-archive" to listOf("ear"),
        "application/x-tika-java-web-archive" to listOf("war"),
        "application/java-serialized-object" to listOf("ser"),
        "application/javascript" to listOf("js"),
        "application/json" to listOf("json"),
        "application/manifest+json" to listOf("webmanifest"),
        "application/java-vm" to listOf("class"),
        "application/x-java-jnilib" to listOf("jnilib"),
        "application/vnd.java.hprof " to listOf("hprof"),
        "application/vnd.java.hprof.text" to listOf("hprof.txt"),
        "application/lost+xml" to listOf("lostxml"),
        "application/mac-binhex40" to listOf("hqx"),
        "application/mac-compactpro" to listOf("cpt"),
        "application/marc" to listOf("mrc"),
        "application/mathematica" to listOf("ma", "nb", "mb"),
        "application/vnd.wolfram.wl" to listOf("wl"),
        "application/mathml+xml" to listOf("mathml"),
        "application/mbox" to listOf("mbox"),
        "application/mediaservercontrol+xml" to listOf("mscml"),
        "application/vnd.mif" to listOf("mif"),
        "application/mp4" to listOf("mp4s"),
        "application/msword" to listOf("doc", "dot"),
        "application/mxf" to listOf("mxf"),
        "application/octet-stream" to listOf(
            "bin",
            "dms",
            "lha",
            "lrf",
            "lzh",
            "so",
            "dist",
            "distz",
            "pkg",
            "bpk",
            "dump",
            "elc",
            "deploy"
        ),
        "application/oda" to listOf("oda"),
        "application/oebps-package+xml" to listOf("opf"),
        "application/ogg" to listOf("ogx"),
        "application/onenote" to listOf("onetmp"),
        "application/onenote;format=one" to listOf("one"),
        "application/onenote;format=onetoc2" to listOf("onetoc", "onetoc2"),
        "application/onenote; format=package" to listOf("onepkg"),
        "application/patch-ops-error+xml" to listOf("xer"),
        "application/pdf" to listOf("pdf"),
        "application/pgp-encrypted" to listOf("pgp", "gpg"),
        "application/pgp-signature" to listOf("asc", "sig"),
        "application/pics-rules" to listOf("prf"),
        "application/pkcs10" to listOf("p10"),
        "application/pkcs7-mime" to listOf("p7m", "p7c"),
        "application/pkcs7-signature" to listOf("p7s"),
        "application/timestamped-data" to listOf("tsd"),
        "application/pkix-cert" to listOf("cer"),
        "application/pkix-crl" to listOf("crl"),
        "application/pkix-pkipath" to listOf("pkipath"),
        "application/pkixcmp" to listOf("pki"),
        "application/pls+xml" to listOf("pls"),
        "application/postscript" to listOf("ps", "eps", "epsf", "epsi"),
        "application/prs.cww" to listOf("cww"),
        "application/rdf+xml" to listOf("rdf", "owl", "df$", "wl$", "xmp"),
        "application/reginfo+xml" to listOf("rif"),
        "application/relax-ng-compact-syntax" to listOf("rnc"),
        "application/resource-lists+xml" to listOf("rl"),
        "application/resource-lists-diff+xml" to listOf("rld"),
        "application/rls-services+xml" to listOf("rs"),
        "application/rsd+xml" to listOf("rsd"),
        "application/rss+xml" to listOf("rss"),
        "application/rtf" to listOf("rtf"),
        "application/sbml+xml" to listOf("sbml"),
        "application/scvp-cv-request" to listOf("scq"),
        "application/scvp-cv-response" to listOf("scs"),
        "application/scvp-vp-request" to listOf("spq"),
        "application/scvp-vp-response" to listOf("spp"),
        "application/sdp" to listOf("sdp"),
        "application/sereal" to listOf("srl"),
        "application/set-payment-initiation" to listOf("setpay"),
        "application/set-registration-initiation" to listOf("setreg"),
        "application/shf+xml" to listOf("shf"),
        "application/smil+xml" to listOf("smi", "smil", "sml"),
        "application/sldworks" to listOf("sldprt", "sldasm", "slddrw"),
        "application/sparql-query" to listOf("rq"),
        "application/sparql-results+xml" to listOf("srx"),
        "application/srgs" to listOf("gram"),
        "application/srgs+xml" to listOf("grxml"),
        "application/ssml+xml" to listOf("ssml"),
        "application/vnd.3gpp.pic-bw-large" to listOf("plb"),
        "application/vnd.3gpp.pic-bw-small" to listOf("psb"),
        "application/vnd.3gpp.pic-bw-var" to listOf("pvb"),
        "application/vnd.3gpp2.tcap" to listOf("tcap"),
        "application/vnd.3m.post-it-notes" to listOf("pwn"),
        "application/vnd.accpac.simply.aso" to listOf("aso"),
        "application/vnd.accpac.simply.imp" to listOf("imp"),
        "application/vnd.acucobol" to listOf("acu"),
        "application/vnd.acucorp" to listOf("atc", "acutc"),
        "application/vnd.adobe.air-application-installer-package+zip" to listOf("air"),
        "application/vnd.adobe.aftereffects.project" to listOf("aep"),
        "application/vnd.adobe.aftereffects.template" to listOf("aet"),
        "application/vnd.adobe.xdp+xml" to listOf("xdp"),
        "application/vnd.adobe.xfdf" to listOf("xfdf"),
        "application/vnd.airzip.filesecure.azf" to listOf("azf"),
        "application/vnd.airzip.filesecure.azs" to listOf("azs"),
        "application/vnd.amazon.ebook" to listOf("azw"),
        "application/vnd.americandynamics.acc" to listOf("acc"),
        "application/vnd.amiga.ami" to listOf("ami"),
        "application/vnd.anser-web-certificate-issue-initiation" to listOf("cii"),
        "application/vnd.anser-web-funds-transfer-initiation" to listOf("fti"),
        "application/vnd.antix.game-component" to listOf("atx"),
        "application/vnd.apple.installer+xml" to listOf("mpkg"),
        "application/vnd.apple.keynote" to listOf("key"),
        "application/vnd.apple.mpegurl" to listOf("m3u8"),
        "application/vnd.apple.pages" to listOf("pages"),
        "application/vnd.apple.numbers" to listOf("numbers"),
        "application/vnd.arastra.swi" to listOf("swi"),
        "application/vnd.blueice.multipass" to listOf("mpm"),
        "application/vnd.bmi" to listOf("bmi"),
        "application/vnd.businessobjects" to listOf("rep"),
        "application/vnd.chemdraw+xml" to listOf("cdxml"),
        "application/vnd.chipnuts.karaoke-mmd" to listOf("mmd"),
        "application/vnd.cinderella" to listOf("cdy"),
        "application/vnd.claymore" to listOf("cla"),
        "application/vnd.clonk.c4group" to listOf("c4g", "c4d", "c4f", "c4p", "c4u"),
        "application/vnd.commonspace" to listOf("csp"),
        "application/vnd.contact.cmsg" to listOf("cdbcmsg"),
        "application/vnd.cosmocaller" to listOf("cmc"),
        "application/vnd.crick.clicker" to listOf("clkx"),
        "application/vnd.crick.clicker.keyboard" to listOf("clkk"),
        "application/vnd.crick.clicker.palette" to listOf("clkp"),
        "application/vnd.crick.clicker.template" to listOf("clkt"),
        "application/vnd.crick.clicker.wordbank" to listOf("clkw"),
        "application/vnd.criticaltools.wbs+xml" to listOf("wbs"),
        "application/vnd.ctc-posml" to listOf("pml"),
        "application/vnd.cups-ppd" to listOf("ppd"),
        "application/vnd.curl.car" to listOf("car"),
        "application/vnd.curl.pcurl" to listOf("pcurl"),
        "application/vnd.data-vision.rdz" to listOf("rdz"),
        "application/vnd.denovo.fcselayout-link" to listOf("fe_launch"),
        "application/vnd.dna" to listOf("dna"),
        "application/vnd.dolby.mlp" to listOf("mlp"),
        "application/vnd.dpgraph" to listOf("dpg"),
        "application/vnd.dreamfactory" to listOf("dfac"),
        "application/vnd.dynageo" to listOf("geo"),
        "application/vnd.ecowin.chart" to listOf("mag"),
        "application/vnd.enliven" to listOf("nml"),
        "application/vnd.epson.esf" to listOf("esf"),
        "application/vnd.epson.msf" to listOf("msf"),
        "application/vnd.epson.quickanime" to listOf("qam"),
        "application/vnd.epson.salt" to listOf("slt"),
        "application/vnd.epson.ssf" to listOf("ssf"),
        "application/vnd.eszigno3+xml" to listOf("es3", "et3"),
        "application/vnd.etsi.asic-e+zip" to listOf("asice"),
        "application/vnd.etsi.asic-s+zip" to listOf("asics"),
        "application/vnd.ezpix-album" to listOf("ez2"),
        "application/vnd.ezpix-package" to listOf("ez3"),
        "application/vnd.fdf" to listOf("fdf"),
        "application/vnd.fdsn.mseed" to listOf("mseed"),
        "application/vnd.fdsn.seed" to listOf("seed", "dataless"),
        "application/vnd.flographit" to listOf("gph"),
        "application/vnd.fluxtime.clip" to listOf("ftc"),
        "application/vnd.framemaker" to listOf("fm", "frame", "maker", "book"),
        "application/vnd.frogans.fnc" to listOf("fnc"),
        "application/vnd.frogans.ltf" to listOf("ltf"),
        "application/vnd.fsc.weblaunch" to listOf("fsc"),
        "application/vnd.fujitsu.oasys" to listOf("oas"),
        "application/vnd.fujitsu.oasys2" to listOf("oa2"),
        "application/vnd.fujitsu.oasys3" to listOf("oa3"),
        "application/vnd.fujitsu.oasysgp" to listOf("fg5"),
        "application/vnd.fujitsu.oasysprs" to listOf("bh2"),
        "application/vnd.fujixerox.ddd" to listOf("ddd"),
        "application/vnd.fujixerox.docuworks" to listOf("xdw"),
        "application/vnd.fujixerox.docuworks.binder" to listOf("xbd"),
        "application/vnd.fuzzysheet" to listOf("fzs"),
        "application/vnd.genomatix.tuxedo" to listOf("txd"),
        "application/vnd.geogebra.file" to listOf("ggb"),
        "application/vnd.geogebra.tool" to listOf("ggt"),
        "application/vnd.geometry-explorer" to listOf("gex", "gre"),
        "application/vnd.gmx" to listOf("gmx"),
        "application/vnd.google-earth.kml+xml" to listOf("kml"),
        "application/vnd.google-earth.kmz" to listOf("kmz"),
        "application/vnd.grafeq" to listOf("gqf", "gqs"),
        "application/vnd.groove-account" to listOf("gac"),
        "application/vnd.groove-help" to listOf("ghf"),
        "application/vnd.groove-identity-message" to listOf("gim"),
        "application/vnd.groove-injector" to listOf("grv"),
        "application/vnd.groove-tool-message" to listOf("gtm"),
        "application/vnd.groove-tool-template" to listOf("tpl"),
        "application/vnd.groove-vcard" to listOf("vcg"),
        "application/vnd.handheld-entertainment+xml" to listOf("zmm"),
        "application/vnd.hbci" to listOf("hbci"),
        "application/vnd.hhe.lesson-player" to listOf("les"),
        "application/vnd.hp-hpgl" to listOf("hpgl"),
        "application/vnd.hp-hpid" to listOf("hpid"),
        "application/vnd.hp-hps" to listOf("hps"),
        "application/vnd.hp-jlyt" to listOf("jlt"),
        "application/vnd.hp-pcl" to listOf("pcl"),
        "application/vnd.hp-pclxl" to listOf("pclxl"),
        "application/vnd.hydrostatix.sof-data" to listOf("sfd-hdstx"),
        "application/vnd.hzn-3d-crossword" to listOf("x3d"),
        "application/vnd.ibm.minipay" to listOf("mpy"),
        "application/vnd.ibm.modcap" to listOf("afp", "listafp", "list3820"),
        "application/vnd.ibm.rights-management" to listOf("irm"),
        "application/vnd.ibm.secure-container" to listOf("sc"),
        "application/vnd.iccprofile" to listOf("icc", "icm"),
        "application/vnd.igloader" to listOf("igl"),
        "application/vnd.immervision-ivp" to listOf("ivp"),
        "application/vnd.immervision-ivu" to listOf("ivu"),
        "application/vnd.intercon.formnet" to listOf("xpw", "xpx"),
        "application/vnd.intu.qbo" to listOf("qbo"),
        "application/vnd.intu.qfx" to listOf("qfx"),
        "application/vnd.iptc.g2.newsmessage+xml" to listOf("nar"),
        "application/vnd.ipunplugged.rcprofile" to listOf("rcprofile"),
        "application/vnd.irepository.package+xml" to listOf("irp"),
        "application/vnd.is-xpr" to listOf("xpr"),
        "application/vnd.jam" to listOf("jam"),
        "application/vnd.jcp.javame.midlet-rms" to listOf("rms"),
        "application/vnd.jisp" to listOf("jisp"),
        "application/vnd.joost.joda-archive" to listOf("joda"),
        "application/vnd.kahootz" to listOf("ktz", "ktr"),
        "application/vnd.kde.karbon" to listOf("karbon"),
        "application/vnd.kde.kchart" to listOf("chrt"),
        "application/vnd.kde.kformula" to listOf("kfo"),
        "application/vnd.kde.kivio" to listOf("flw"),
        "application/vnd.kde.kontour" to listOf("kon"),
        "application/vnd.kde.kpresenter" to listOf("kpr", "kpt"),
        "application/vnd.kde.kspread" to listOf("ksp"),
        "application/vnd.kde.kword" to listOf("kwd", "kwt"),
        "application/vnd.kenameaapp" to listOf("htke"),
        "application/vnd.kidspiration" to listOf("kia"),
        "application/vnd.kinar" to listOf("kne", "knp"),
        "application/vnd.koan" to listOf("skp", "skd", "skt", "skm"),
        "application/vnd.kodak-descriptor" to listOf("sse"),
        "application/vnd.llamagraphics.life-balance.desktop" to listOf("lbd"),
        "application/vnd.llamagraphics.life-balance.exchange+xml" to listOf("lbe"),
        "application/vnd.lotus-1-2-3" to listOf("wk1", "wk2", "wk3", "wk4", "123"),
        "application/vnd.lotus-1-2-3;version=2" to listOf("wk1", "wk2"),
        "application/vnd.lotus-1-2-3;version=3" to listOf("wk3"),
        "application/vnd.lotus-1-2-3;version=4" to listOf("wk4"),
        "application/vnd.lotus-1-2-3;version=97+9.x" to listOf("123"),
        "application/vnd.lotus-approach" to listOf("apr"),
        "application/vnd.lotus-freelance" to listOf("pre"),
        "application/vnd.lotus-notes" to listOf("nsf"),
        "application/vnd.lotus-organizer" to listOf("org"),
        "application/vnd.lotus-wordpro" to listOf("lwp"),
        "application/vnd.macports.portpkg" to listOf("portpkg"),
        "application/vnd.mcd" to listOf("mcd"),
        "application/vnd.medcalcdata" to listOf("mc1"),
        "application/vnd.mediastation.cdkey" to listOf("cdkey"),
        "application/vnd.mfer" to listOf("mwf"),
        "application/vnd.mfmp" to listOf("mfm"),
        "application/vnd.micrografx.flo" to listOf("flo"),
        "application/vnd.micrografx.igx" to listOf("igx"),
        "application/vnd.mif" to listOf("mif"),
        "application/vnd.mindjet.mindmanager" to listOf("mmp", "mmap", "mmpt", "mmat", "mmmp", "mmas"),
        "application/vnd.mobius.daf" to listOf("daf"),
        "application/vnd.mobius.dis" to listOf("dis"),
        "application/vnd.mobius.mbk" to listOf("mbk"),
        "application/vnd.mobius.mqy" to listOf("mqy"),
        "application/vnd.mobius.msl" to listOf("msl"),
        "application/vnd.mobius.plc" to listOf("plc"),
        "application/vnd.mobius.txf" to listOf("txf"),
        "application/vnd.mophun.application" to listOf("mpn"),
        "application/vnd.mophun.certificate" to listOf("mpc"),
        "application/vnd.mozilla.xul+xml" to listOf("xul"),
        "application/vnd.ms-artgalry" to listOf("cil"),
        "application/vnd.ms-cab-compressed" to listOf("cab"),
        "application/vnd.ms-excel" to listOf("xls", "xlm", "xla", "xlc", "xlt", "xlw", "xll", "xld"),
        "application/vnd.ms-excel.addin.macroenabled.12" to listOf("xlam"),
        "application/vnd.ms-excel.sheet.macroenabled.12" to listOf("xlsm"),
        "application/vnd.ms-excel.sheet.binary.macroenabled.12" to listOf("xlsb"),
        "application/vnd.ms-fontobject" to listOf("eot"),
        "application/vnd.ms-htmlhelp" to listOf("chm"),
        "application/vnd.ms-ims" to listOf("ims"),
        "application/vnd.ms-lrm" to listOf("lrm"),
        "application/vnd.ms-outlook" to listOf("msg"),
        "application/vnd.ms-outlook-pst" to listOf("pst", "ost"),
        "application/vnd.ms-pki.seccat" to listOf("cat"),
        "application/vnd.ms-pki.stl" to listOf("stl"),
        "application/vnd.ms-powerpoint" to listOf("ppt", "ppz", "pps", "pot", "ppa"),
        "application/vnd.ms-powerpoint.addin.macroenabled.12" to listOf("ppam"),
        "application/vnd.ms-powerpoint.presentation.macroenabled.12" to listOf("pptm"),
        "application/vnd.ms-powerpoint.slide.macroenabled.12" to listOf("sldm"),
        "application/vnd.ms-powerpoint.slideshow.macroenabled.12" to listOf("ppsm"),
        "application/vnd.ms-powerpoint.template.macroenabled.12" to listOf("potm"),
        "application/vnd.ms-project" to listOf("mpp", "mpt"),
        "application/x-project" to listOf("mpx"),
        "application/vnd.ms-word.document.macroenabled.12" to listOf("docm"),
        "application/vnd.ms-word.template.macroenabled.12" to listOf("dotm"),
        "application/vnd.ms-works" to listOf("wps", "wks", "wcm", "wdb"),
        "application/vnd.ms-wpl" to listOf("wpl"),
        "application/vnd.ms-xpsdocument" to listOf("xps", "oxps"),
        "application/vnd.msa-disk-image" to listOf("msa"),
        "application/vnd.mseq" to listOf("mseq"),
        "application/vnd.musician" to listOf("mus"),
        "application/vnd.muvee.style" to listOf("msty"),
        "application/vnd.neurolanguage.nlu" to listOf("nlu"),
        "application/vnd.noblenet-directory" to listOf("nnd"),
        "application/vnd.noblenet-sealer" to listOf("nns"),
        "application/vnd.noblenet-web" to listOf("nnw"),
        "application/vnd.nokia.n-gage.data" to listOf("ngdat"),
        "application/vnd.nokia.n-gage.symbian.install" to listOf("n-gage"),
        "application/vnd.nokia.radio-preset" to listOf("rpst"),
        "application/vnd.nokia.radio-presets" to listOf("rpss"),
        "application/vnd.novadigm.edm" to listOf("edm"),
        "application/vnd.novadigm.edx" to listOf("edx"),
        "application/vnd.novadigm.ext" to listOf("ext"),
        "application/vnd.oasis.opendocument.chart" to listOf("odc"),
        "application/vnd.oasis.opendocument.chart-template" to listOf("otc"),
        "application/vnd.oasis.opendocument.base" to listOf("odb"),
        "application/vnd.oasis.opendocument.formula" to listOf("odf"),
        "application/vnd.oasis.opendocument.formula-template" to listOf("odft"),
        "application/vnd.oasis.opendocument.graphics" to listOf("odg"),
        "application/vnd.oasis.opendocument.graphics-template" to listOf("otg"),
        "application/vnd.oasis.opendocument.image" to listOf("odi"),
        "application/vnd.oasis.opendocument.image-template" to listOf("oti"),
        "application/vnd.oasis.opendocument.presentation" to listOf("odp"),
        "application/vnd.oasis.opendocument.presentation-template" to listOf("otp"),
        "application/vnd.oasis.opendocument.spreadsheet" to listOf("ods"),
        "application/vnd.oasis.opendocument.spreadsheet-template" to listOf("ots"),
        "application/vnd.oasis.opendocument.text" to listOf("odt"),
        "application/vnd.oasis.opendocument.flat.text" to listOf("fodt"),
        "application/vnd.oasis.opendocument.flat.presentation" to listOf("fodp"),
        "application/vnd.oasis.opendocument.flat.spreadsheet" to listOf("fods"),
        "application/vnd.oasis.opendocument.text-master" to listOf("otm"),
        "application/vnd.oasis.opendocument.text-template" to listOf("ott"),
        "application/vnd.oasis.opendocument.text-web" to listOf("oth"),
        "application/vnd.olpc-sugar" to listOf("xo"),
        "application/vnd.oma.dd2+xml" to listOf("dd2"),
        "application/vnd.openofficeorg.extension" to listOf("oxt"),
        "application/vnd.openofficeorg.autotext" to listOf("bau"),
        "application/vnd.openxmlformats-officedocument.presentationml.presentation" to listOf("pptx", "thmx"),
        "application/vnd.openxmlformats-officedocument.presentationml.slide" to listOf("sldx"),
        "application/vnd.openxmlformats-officedocument.presentationml.template" to listOf("potx"),
        "application/vnd.openxmlformats-officedocument.presentationml.slideshow" to listOf("ppsx"),
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" to listOf("xlsx"),
        "application/vnd.openxmlformats-officedocument.spreadsheetml.template" to listOf("xltx"),
        "application/vnd.ms-excel.template.macroenabled.12" to listOf("xltm"),
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document" to listOf("docx"),
        "application/vnd.openxmlformats-officedocument.wordprocessingml.template" to listOf("dotx"),
        "application/vnd.osgi.dp" to listOf("dp"),
        "application/vnd.palm" to listOf("pqa", "oprc"),
        "application/vnd.pg.format" to listOf("str"),
        "application/vnd.pg.osasli" to listOf("ei6"),
        "application/vnd.picsel" to listOf("efif"),
        "application/vnd.pocketlearn" to listOf("plf"),
        "application/vnd.powerbuilder6" to listOf("pbd"),
        "application/vnd.previewsystems.box" to listOf("box"),
        "application/vnd.proteus.magazine" to listOf("mgz"),
        "application/vnd.publishare-delta-tree" to listOf("qps"),
        "application/vnd.pvi.ptid1" to listOf("ptid"),
        "application/vnd.quark.quarkxpress" to listOf("qxd", "qxt", "qwd", "qwt", "qxl", "qxb"),
        "application/vnd.recordare.musicxml" to listOf("mxl"),
        "application/vnd.recordare.musicxml+xml" to listOf("musicxml"),
        "application/vnd.rim.cod" to listOf("cod"),
        "application/vnd.rn-realmedia" to listOf("rm"),
        "application/vnd.route66.link66+xml" to listOf("link66"),
        "application/vnd.seemail" to listOf("see"),
        "application/vnd.sema" to listOf("sema"),
        "application/vnd.semd" to listOf("semd"),
        "application/vnd.semf" to listOf("semf"),
        "application/vnd.shana.informed.formdata" to listOf("ifm"),
        "application/vnd.shana.informed.formtemplate" to listOf("itp"),
        "application/vnd.shana.informed.interchange" to listOf("iif"),
        "application/vnd.shana.informed.package" to listOf("ipk"),
        "application/vnd.simtech-mindmapper" to listOf("twd", "twds"),
        "application/vnd.smaf" to listOf("mmf"),
        "application/vnd.smart.teacher" to listOf("teacher"),
        "application/vnd.solent.sdkm+xml" to listOf("sdkm", "sdkd"),
        "application/vnd.spotfire.dxp" to listOf("dxp"),
        "application/vnd.spotfire.sfs" to listOf("sfs"),
        "application/vnd.stardivision.calc" to listOf("sdc"),
        "application/vnd.stardivision.draw" to listOf("sda"),
        "application/vnd.stardivision.impress" to listOf("sdd"),
        "application/vnd.stardivision.math" to listOf("smf"),
        "application/vnd.stardivision.writer" to listOf("sdw"),
        "application/x-staroffice-template" to listOf("vor"),
        "application/x-subrip" to listOf("srt"),
        "application/vnd.sun.xml.writer" to listOf("sxw"),
        "application/vnd.sun.xml.writer.template" to listOf("stw"),
        "application/vnd.sun.xml.calc" to listOf("sxc"),
        "application/vnd.sun.xml.draw" to listOf("sxd"),
        "application/vnd.sun.xml.impress" to listOf("sxi"),
        "application/vnd.stardivision.writer-global" to listOf("sgl"),
        "application/vnd.sun.xml.calc" to listOf("sxc"),
        "application/vnd.sun.xml.calc.template" to listOf("stc"),
        "application/vnd.sun.xml.draw" to listOf("sxd"),
        "application/vnd.sun.xml.draw.template" to listOf("std"),
        "application/vnd.sun.xml.impress" to listOf("sxi"),
        "application/vnd.sun.xml.impress.template" to listOf("sti"),
        "application/vnd.sun.xml.math" to listOf("sxm"),
        "application/vnd.sun.xml.writer" to listOf("sxw"),
        "application/vnd.sun.xml.writer.global" to listOf("sxg"),
        "application/vnd.sun.xml.writer.template" to listOf("stw"),
        "application/vnd.sus-calendar" to listOf("sus", "susp"),
        "application/vnd.svd" to listOf("svd"),
        "application/vnd.symbian.install" to listOf("sis", "sisx"),
        "application/vnd.syncml+xml" to listOf("xsm"),
        "application/vnd.syncml.dm+wbxml" to listOf("bdm"),
        "application/vnd.syncml.dm+xml" to listOf("xdm"),
        "application/vnd.tao.intent-module-archive" to listOf("tao"),
        "application/vnd.tcpdump.pcap" to listOf("pcap", "cap", "dmp"),
        "application/vnd.tcpdump.pcapng" to listOf("pcapng"),
        "application/vnd.tmobile-livetv" to listOf("tmo"),
        "application/x-tmx" to listOf("tmx"),
        "application/vnd.trid.tpt" to listOf("tpt"),
        "application/vnd.triscape.mxs" to listOf("mxs"),
        "application/vnd.trueapp" to listOf("tra"),
        "application/vnd.ufdl" to listOf("ufd", "ufdl"),
        "application/ttml+xml" to listOf("ttml"),
        "application/vnd.uiq.theme" to listOf("utz"),
        "application/vnd.umajin" to listOf("umj"),
        "application/vnd.unity" to listOf("unityweb"),
        "application/vnd.uoml+xml" to listOf("uoml"),
        "application/vnd.vcx" to listOf("vcx"),
        "application/vnd.visio" to listOf("vsd", "vst", "vss", "vsw"),
        "application/vnd.ms-visio.drawing" to listOf("vsdx"),
        "application/vnd.ms-visio.template" to listOf("vstx"),
        "application/vnd.ms-visio.stencil" to listOf("vssx"),
        "application/vnd.ms-visio.drawing.macroEnabled.12" to listOf("vsdm"),
        "application/vnd.ms-visio.template.macroEnabled.12" to listOf("vstm"),
        "application/vnd.ms-visio.stencil.macroEnabled.12" to listOf("vssm"),
        "application/vnd.visionary" to listOf("vis"),
        "application/vnd.vsf" to listOf("vsf"),
        "application/vnd.wap.wbxml" to listOf("wbxml"),
        "application/vnd.wap.wmlc" to listOf("wmlc"),
        "application/vnd.wap.wmlscriptc" to listOf("wmlsc"),
        "application/vnd.webturbo" to listOf("wtb"),
        "application/vnd.wordperfect" to listOf("wpd", "wp", "wp5", "wp6", "w60", "wp61", "wpt"),
        "application/vnd.wqd" to listOf("wqd"),
        "application/vnd.wt.stf" to listOf("stf"),
        "application/vnd.xara" to listOf("xar"),
        "application/vnd.xfdl" to listOf("xfdl"),
        "application/vnd.yamaha.hv-dic" to listOf("hvd"),
        "application/vnd.yamaha.hv-script" to listOf("hvs"),
        "application/vnd.yamaha.hv-voice" to listOf("hvp"),
        "application/vnd.yamaha.openscoreformat" to listOf("osf"),
        "application/vnd.yamaha.openscoreformat.osfpvg+xml" to listOf("osfpvg"),
        "application/vnd.yamaha.smaf-audio" to listOf("saf"),
        "application/vnd.yamaha.smaf-phrase" to listOf("spf"),
        "application/vnd.yellowriver-custom-menu" to listOf("cmp"),
        "application/vnd.zul" to listOf("zir", "zirz"),
        "application/vnd.zzazz.deck+xml" to listOf("zaz"),
        "application/voicexml+xml" to listOf("vxml"),
        "application/warc" to listOf("warc"),
        "application/wasm" to listOf("wasm"),
        "application/winhlp" to listOf("hlp"),
        "application/wsdl+xml" to listOf("wsdl"),
        "application/wspolicy+xml" to listOf("wspolicy"),
        "image/x-tga" to listOf("tga", "icb", "vda"),
        "application/x-abiword" to listOf("abw"),
        "application/x-ace-compressed" to listOf("ace"),
        "application/x-axcrypt" to listOf("axx"),
        "application/x-adobe-indesign" to listOf("indd"),
        "application/vnd.isac.fcs" to listOf("fcs"),
        "application/vnd.adobe.indesign-idml-package" to listOf("idml"),
        "application/x-adobe-indesign-interchange" to listOf("inx"),
        "application/x-apple-diskimage" to listOf("dmg"),
        "application/x-appleworks" to listOf("cwk"),
        "application/x-archive" to listOf("ar", "a"),
        "application/x-arj" to listOf("arj"),
        "application/x-asprs" to listOf("las", "laz"),
        "application/x-authorware-bin" to listOf("aab", "x32", "u32", "vox"),
        "application/x-authorware-map" to listOf("aam"),
        "application/x-authorware-seg" to listOf("aas"),
        "application/x-bcpio" to listOf("bcpio"),
        "application/x-bibtex-text-file" to listOf("bib", "bibtex"),
        "application/x-bittorrent" to listOf("torrent"),
        "application/x-gtar" to listOf("gtar"),
        "application/x-amiga-disk-format" to listOf("adf"),
        "application/x-brotli" to listOf("br", "brotli"),
        "application/x-bzip" to listOf("bz", "tbz"),
        "application/x-bzip2" to listOf("bz2", "tbz2", "boz"),
        "application/x-cdlink" to listOf("vcd"),
        "application/x-chat" to listOf("chat"),
        "application/x-chess-pgn" to listOf("pgn"),
        "application/x-chrome-package" to listOf("crx"),
        "application/x-compress" to listOf("z"),
        "application/x-corelpresentations" to listOf("shw"),
        "application/x-cpio" to listOf("cpio"),
        "application/x-csh" to listOf("csh", "tcsh"),
        "application/x-debian-package" to listOf("deb", "udeb"),
        "application/x-dex" to listOf("dex"),
        "application/x-director" to listOf("dir", "dcr", "dxr", "cst", "cct", "cxt", "w3d", "fgd", "swa"),
        "application/x-doom" to listOf("wad"),
        "application/x-dtbncx+xml" to listOf("ncx"),
        "application/x-dtbook+xml" to listOf("dtb"),
        "application/x-dtbresource+xml" to listOf("res"),
        "application/x-dvi" to listOf("dvi"),
        "application/x-elc" to listOf("elc"),
        "message/x-emlx" to listOf("emlx"),
        "application/x-endnote-refer" to listOf("enw", "enr"),
        "application/x-endnote-style" to listOf("ens"),
        "application/x-killustrator" to listOf("kil"),
        "application/x-dosexec" to listOf("exe"),
        "application/x-erdas-hfa" to listOf("hfa"),
        "application/x-filemaker" to listOf("fp7"),
        "application/x-font-bdf" to listOf("bdf"),
        "application/x-font-ghostscript" to listOf("gsf"),
        "application/x-font-linux-psf" to listOf("psf"),
        "application/x-font-otf" to listOf("otf"),
        "application/x-font-pcf" to listOf("pcf"),
        "application/x-font-snf" to listOf("snf"),
        "application/x-font-ttf" to listOf("ttf", "ttc"),
        "application/x-font-type1" to listOf("pfa", "pfb"),
        "application/x-font-adobe-metric" to listOf("afm", "acfm", "amfm"),
        "application/x-font-printer-metric" to listOf("pfm"),
        "application/x-futuresplash" to listOf("spl"),
        "application/x-gnucash" to listOf("gnucash"),
        "application/x-gnumeric" to listOf("gnumeric"),
        "application/x-grib" to listOf("grb", "grb1", "grb2"),
        "application/gzip" to listOf("gz", "tgz", "gz"),
        "application/zstd" to listOf("zst"),
        "application/x-esri-layer" to listOf("lyr"),
        "application/x-hdf" to listOf("hdf", "he5", "h5"),
        "application/x-ibooks+zip" to listOf("ibooks"),
        "application/x-internet-archive" to listOf("arc"),
        "application/x-isatab-investigation" to listOf("*.txt"),
        "application/x-isatab" to listOf("*.txt"),
        "application/x-isatab-assay" to listOf("*.txt"),
        "application/x-iso9660-image" to listOf("iso"),
        "application/x-itunes-ipa" to listOf("ipa"),
        "application/x-java-jnlp-file" to listOf("jnlp"),
        "application/x-java-pack200" to listOf("pack"),
        "application/x-jeol-jdf" to listOf("jdf"),
        "application/x-latex" to listOf("latex"),
        "application/x-lz4" to listOf("lz4"),
        "application/x-lzip" to listOf("lz"),
        "application/x-lzma" to listOf("lzma"),
        "application/x-memgraph" to listOf("memgraph"),
        "application/x-mobipocket-ebook" to listOf("prc", "mobi"),
        "application/x-ms-application" to listOf("application"),
        "application/x-ms-wmd" to listOf("wmd"),
        "application/x-ms-wmz" to listOf("wmz"),
        "application/x-ms-xbap" to listOf("xbap"),
        "application/x-msaccess" to listOf("mdb"),
        "application/x-msbinder" to listOf("obd"),
        "application/x-mscardfile" to listOf("crd"),
        "application/x-msclip" to listOf("clp"),
        "application/x-msdownload" to listOf("dll", "com"),
        "application/x-ms-installer" to listOf("msi", "msp", "mst"),
        "application/x-msmediaview" to listOf("mvb", "m13", "m14"),
        "application/x-msmoney" to listOf("mny"),
        "application/x-mspublisher" to listOf("pub"),
        "application/x-msschedule" to listOf("scd"),
        "application/x-msterminal" to listOf("trm"),
        "application/x-mswrite" to listOf("wri"),
        "application/x-mysql-misam-compressed-index" to listOf("MYI"),
        "application/x-mysql-misam-data" to listOf("MYD"),
        "application/x-nesrom" to listOf("nes"),
        "application/x-netcdf" to listOf("nc", "cdf"),
        "application/x-parquet" to listOf("parquet"),
        "application/x-pkcs12" to listOf("p12", "pfx"),
        "application/x-pkcs7-certificates" to listOf("p7b", "spc"),
        "application/x-pkcs7-certreqresp" to listOf("p7r"),
        "application/x-prt" to listOf("prt"),
        "application/x-quattro-pro" to listOf("wq1", "wq2", "wkq", "qpw", "wb1", "wb2", "wb3"),
        "application/x-quattro-pro;version=1-4" to listOf("wq1", "wkq"),
        "application/x-quattro-pro;version=5" to listOf("wq2", "wkq"),
        "application/x-quattro-pro;version=1+5" to listOf("wb1"),
        "application/x-quattro-pro;version=6" to listOf("wb2"),
        "application/xquery" to listOf("xq", "xquery"),
        "application/x-rar-compressed" to listOf("rar"),
        "application/x-roxio-toast" to listOf("toast"),
        "application/x-rpm" to listOf("rpm"),
        "application/x-sas" to listOf("sas"),
        "application/x-sas-program-data" to listOf("ss7", "sas7bpgm"),
        "application/x-sas-audit" to listOf("st7", "sas7baud"),
        "application/x-sas-data-v6" to listOf("sd2"),
        "application/x-sas-data" to listOf("sd7", "sas7bdat"),
        "application/x-sas-view" to listOf("sv7", "sas7bvew"),
        "application/x-sas-data-index" to listOf("si7", "sas7bndx"),
        "application/x-sas-catalog" to listOf("sc7", "sas7bcat"),
        "application/x-sas-access" to listOf("sa7", "sas7bacs"),
        "application/x-sas-fdb" to listOf("sf7", "sas7bfdb"),
        "application/x-sas-mddb" to listOf("sm7", "sas7bmdb"),
        "application/x-sas-dmdb" to listOf("s7m", "sas7bdmd"),
        "application/x-sas-itemstor" to listOf("sr7", "sas7bitm"),
        "application/x-sas-utility" to listOf("su7", "sas7butl"),
        "application/x-sas-putility" to listOf("sp7", "sas7bput"),
        "application/x-sas-transport" to listOf("stx"),
        "application/x-sas-backup" to listOf("sas7bbak"),
        "application/x-sas-xport" to listOf("xpt", "xport"),
        "application/x-spss-sav" to listOf("sav"),
        "application/x-sh" to listOf("sh", "bash"),
        "application/x-shar" to listOf("shar"),
        "application/x-shapefile" to listOf("shp"),
        "application/x-shockwave-flash" to listOf("swf"),
        "application/x-sibelius" to listOf("sib"),
        "application/x-silverlight-app" to listOf("xap"),
        "application/x-snappy-framed" to listOf("sz"),
        "application/x-sfdu" to listOf("sfdu"),
        "application/x-spectrum-tzx" to listOf("tzx"),
        "application/x-stata-do" to listOf("do"),
        "application/x-stata-dta" to listOf("dta"),
        "application/x-stuffit" to listOf("sit"),
        "application/x-stuffitx" to listOf("sitx"),
        "application/x-sv4cpio" to listOf("sv4cpio"),
        "application/x-sv4crc" to listOf("sv4crc"),
        "application/x-tar" to listOf("tar"),
        "application/x-tex" to listOf("tex"),
        "application/x-tex-tfm" to listOf("tfm"),
        "application/x-texinfo" to listOf("texinfo", "texi"),
        "application/x-tika-msworks-spreadsheet" to listOf("xlr"),
        "application/x-uc2-compressed" to listOf("uc2"),
        "application/x-ustar" to listOf("ustar"),
        "application/x-vmdk" to listOf("vmdk"),
        "application/x-wais-source" to listOf("src"),
        "application/x-webarchive" to listOf("webarchive"),
        "application/x-x509-cert" to listOf("crt"),
        "application/x-x509-cert;format=pem" to listOf("pem"),
        "application/x-x509-cert;format=der" to listOf("der"),
        "application/x-xfig" to listOf("fig"),
        "application/x-xpinstall" to listOf("xpi"),
        "application/x-xmind" to listOf("xmind"),
        "application/x-xz" to listOf("xz"),
        "application/x-zoo" to listOf("zoo"),
        "application/xenc+xml" to listOf("xenc"),
        "application/xhtml+xml" to listOf("xhtml", "xhtml2", "xht"),
        "application/xml" to listOf("xml", "xsl", "xsd"),
        "application/xml-dtd" to listOf("dtd"),
        "application/xop+xml" to listOf("xop"),
        "application/xslfo+xml" to listOf("xslfo", "fo"),
        "application/xslt+xml" to listOf("xslt"),
        "application/xspf+xml" to listOf("xspf"),
        "application/xv+xml" to listOf("mxml", "xhvml", "xvml", "xvm"),
        "application/zip" to listOf("zip"),
        "application/x-7z-compressed" to listOf("7z"),
        "audio/ac3" to listOf("ac3"),
        "audio/adpcm" to listOf("adp"),
        "audio/amr" to listOf("amr"),
        "audio/basic" to listOf("au", "snd"),
        "audio/midi" to listOf("mid", "midi", "kar", "rmi"),
        "audio/mp4" to listOf("mp4a", "m4a", "m4b"),
        "audio/mpeg" to listOf("mpga", "mp2", "mp2a", "mp3", "m2a", "m3a"),
        "audio/ogg" to listOf("oga"),
        "audio/vorbis" to listOf("ogg"),
        "audio/x-psf" to listOf("psf1", "psflib", "minipsf", "minipsf1", "gslib", "minigsf"),
        "audio/x-sap" to listOf("sap"),
        "audio/opus" to listOf("opus"),
        "audio/speex" to listOf("spx"),
        "audio/vnd.adobe.soundbooth" to listOf("asnd"),
        "audio/vnd.digital-winds" to listOf("eol"),
        "audio/vnd.dts" to listOf("dts"),
        "audio/vnd.dts.hd" to listOf("dtshd"),
        "audio/vnd.lucent.voice" to listOf("lvp"),
        "audio/vnd.ms-playready.media.pya" to listOf("pya"),
        "audio/vnd.nuera.ecelp4800" to listOf("ecelp4800"),
        "audio/vnd.nuera.ecelp7470" to listOf("ecelp7470"),
        "audio/vnd.nuera.ecelp9600" to listOf("ecelp9600"),
        "audio/x-aac" to listOf("aac"),
        "audio/x-aiff" to listOf("aif", "aiff", "aifc"),
        "audio/x-caf" to listOf("caf"),
        "audio/x-flac" to listOf("flac"),
        "audio/x-mod" to listOf("mod"),
        "audio/x-mpegurl" to listOf("m3u"),
        "audio/x-ms-wax" to listOf("wax"),
        "audio/x-ms-wma" to listOf("wma"),
        "audio/x-pn-realaudio" to listOf("ram", "ra"),
        "audio/x-pn-realaudio-plugin" to listOf("rmp"),
        "audio/vnd.wave" to listOf("wav"),
        "chemical/x-cdx" to listOf("cdx"),
        "chemical/x-cif" to listOf("cif"),
        "chemical/x-cmdf" to listOf("cmdf"),
        "chemical/x-cml" to listOf("cml"),
        "chemical/x-csml" to listOf("csml"),
        "chemical/x-pdb" to listOf("pdb"),
        "chemical/x-xyz" to listOf("xyz"),
        "image/x-3ds" to listOf("3ds"),
        "image/aces" to listOf("exr"),
        "image/bmp" to listOf("bmp", "dib"),
        "image/x-bpg" to listOf("bpg"),
        "image/cgm" to listOf("cgm"),
        "image/x-dpx" to listOf("dpx"),
        "image/emf" to listOf("emf"),
        "image/x-emf-compressed" to listOf("emz"),
        "image/g3fax" to listOf("g3"),
        "image/gif" to listOf("gif"),
        "image/avif" to listOf("avif"),
        "image/heif" to listOf("heif"),
        "image/heic" to listOf("heic"),
        "image/icns" to listOf("icns"),
        "image/ief" to listOf("ief"),
        "image/jp2" to listOf("jp2"),
        "image/jpeg" to listOf("jpg", "jpeg", "jpe", "jif", "jfif", "jfi"),
        "image/jpm" to listOf("jpm", "jpgm"),
        "image/jpx" to listOf("jpf"),
        "image/nitf" to listOf("ntf", "nitf"),
        "image/png" to listOf("png"),
        "image/prs.btif" to listOf("btif"),
        "image/svg+xml" to listOf("svg", "svgz"),
        "image/tiff" to listOf("tiff", "tif"),
        "image/vnd.adobe.photoshop" to listOf("psd"),
        "image/vnd.adobe.premiere" to listOf("ppj"),
        "image/vnd.dgn" to listOf("dgn", "dgnlib", "cel"),
        "image/vnd.djvu" to listOf("djvu", "djv"),
        "image/vnd.dwg" to listOf("dwg"),
        "image/vnd.dxb" to listOf("dxb"),
        "image/vnd.dxf" to listOf("dxf"),
        "image/vnd.fastbidsheet" to listOf("fbs"),
        "image/vnd.fpx" to listOf("fpx"),
        "image/vnd.fst" to listOf("fst"),
        "image/vnd.fujixerox.edmics-mmr" to listOf("mmr"),
        "image/vnd.fujixerox.edmics-rlc" to listOf("rlc"),
        "image/vnd.microsoft.icon" to listOf("ico"),
        "image/vnd.ms-modi" to listOf("mdi"),
        "image/vnd.net-fpx" to listOf("npx"),
        "image/vnd.wap.wbmp" to listOf("wbmp"),
        "image/vnd.zbrush.dcx" to listOf("dcx"),
        "image/vnd.zbrush.pcx" to listOf("pcx"),
        "image/webp" to listOf("webp"),
        "image/heic" to listOf("heic"),
        "image/heif" to listOf("heif"),
        "image/wmf" to listOf("wmf"),
        "image/vnd.xiff" to listOf("xif"),
        "image/x-cmu-raster" to listOf("ras"),
        "image/x-cmx" to listOf("cmx"),
        "image/x-freehand" to listOf(
            "fh",
            "fhc",
            "fh4",
            "fh40",
            "fh5",
            "fh50",
            "fh7",
            "fh8",
            "fh9",
            "fh10",
            "fh11",
            "fh12",
            "ft7",
            "ft8",
            "ft9",
            "ft10",
            "ft11",
            "ft12"
        ),
        "image/x-jbig2" to listOf("jb2", "jbig2"),
        "image/x-jp2-codestream" to listOf("j2c"),
        "image/jxl" to listOf("jxl"),
        "image/x-pict" to listOf("pic", "pct", "pict"),
        "image/x-portable-anymap" to listOf("pnm"),
        "image/x-portable-bitmap" to listOf("pbm"),
        "image/x-portable-graymap" to listOf("pgm"),
        "image/x-portable-pixmap" to listOf("ppm"),
        "image/x-raw-adobe" to listOf("dng"),
        "image/x-raw-hasselblad" to listOf("3fr"),
        "image/x-raw-fuji" to listOf("raf"),
        "image/x-raw-canon" to listOf("crw"),
        "image/x-canon-cr2" to listOf("cr2"),
        "image/x-canon-cr3" to listOf("cr3"),
        "image/x-raw-kodak" to listOf("k25", "kdc", "dcs", "drf"),
        "image/x-raw-minolta" to listOf("mrw"),
        "image/x-raw-nikon" to listOf("nef", "nrw"),
        "image/x-raw-olympus" to listOf("orf"),
        "image/x-raw-pentax" to listOf("ptx", "pef"),
        "image/x-raw-sony" to listOf("arw", "srf", "sr2"),
        "image/x-raw-sigma" to listOf("x3f"),
        "image/x-raw-epson" to listOf("erf"),
        "image/x-raw-mamiya" to listOf("mef"),
        "image/x-raw-leaf" to listOf("mos"),
        "image/x-raw-panasonic" to listOf("raw", "rw2"),
        "image/x-raw-phaseone" to listOf("iiq"),
        "image/x-raw-red" to listOf("r3d"),
        "image/x-raw-imacon" to listOf("fff"),
        "image/x-raw-logitech" to listOf("pxn"),
        "image/x-raw-casio" to listOf("bay"),
        "image/x-raw-rawzor" to listOf("rwz"),
        "image/x-rgb" to listOf("rgb"),
        "image/x-xbitmap" to listOf("xbm"),
        "image/x-xcf" to listOf("xcf"),
        "image/x-xpixmap" to listOf("xpm"),
        "image/x-xwindowdump" to listOf("xwd"),
        "message/rfc822" to listOf("eml", "mime"),
        "multipart/related" to listOf("mht", "mhtml"),
        "model/e57" to listOf("e57"),
        "model/iges" to listOf("igs", "iges"),
        "model/mesh" to listOf("msh", "mesh", "silo"),
        "model/vnd.dwf" to listOf("dwf"),
        "model/vnd.dwfx+xps" to listOf("dwfx"),
        "model/vnd.gdl" to listOf("gdl"),
        "model/vnd.gtw" to listOf("gtw"),
        "model/vnd.mts" to listOf("mts"),
        "model/vnd.vtu" to listOf("vtu"),
        "model/vrml" to listOf("wrl", "vrml"),
        "application/dif+xml" to listOf("dif"),
        "text/x-actionscript" to listOf("as"),
        "text/x-ada" to listOf("ada", "adb", "ads"),
        "text/x-applescript" to listOf("applescript"),
        "text/asp" to listOf("asp"),
        "text/aspdotnet" to listOf("aspx"),
        "text/x-aspectj" to listOf("aj"),
        "text/x-assembly" to listOf("s", "S", "asm"),
        "text/calendar" to listOf("ics", "ifb"),
        "text/x-config" to listOf("config", "conf", "cfg", "xconf"),
        "text/css" to listOf("css"),
        "text/csv" to listOf("csv"),
        "text/html" to listOf("html", "htm"),
        "text/x-makefile" to listOf("kefile", "UMakefile"),
        "text/plain" to listOf(
            "txt",
            "text",
            "def",
            "list",
            "in",
            "STALL",
            "YS",
            "CENSE",
            "TICE",
            "ADME",
            "s-linkmap",
            "s-menulinks",
            "aart",
            "ac",
            "am",
            "apt",
            "bsh",
            "classpath",
            "cnd",
            "cwiki",
            "data",
            "dcl",
            "dsp",
            "dsw",
            "egrm",
            "ent",
            "ft",
            "fn",
            "fv",
            "grm",
            "g",
            "taccess",
            "handlers",
            "htc",
            "ihtml",
            "jmx",
            "junit",
            "jx",
            "manifest",
            "m4",
            "mf",
            "MF",
            "meta",
            "mdo",
            "n3",
            "pen",
            "pod",
            "pom",
            "project",
            "rng",
            "rnx",
            "roles",
            "schemas",
            "tld",
            "types",
            "vm",
            "vsl",
            "wsdd",
            "xargs",
            "xcat",
            "xegrm",
            "xgrm",
            "xlex",
            "xlog",
            "xmap",
            "xroles",
            "xsamples",
            "xsp",
            "xtest",
            "xweb",
            "xwelcome"
        ),
        "text/prs.lines.tag" to listOf("dsc"),
        "text/richtext" to listOf("rtx"),
        "text/sgml" to listOf("sgml", "sgm"),
        "text/tab-separated-values" to listOf("tsv"),
        "text/troff" to listOf("t", "tr", "roff", "nroff", "man", "me", "ms"),
        "text/uri-list" to listOf("uri", "uris", "urls"),
        "text/vnd.curl" to listOf("curl"),
        "text/vnd.curl.dcurl" to listOf("dcurl"),
        "text/vnd.curl.scurl" to listOf("scurl"),
        "text/vnd.curl.mcurl" to listOf("mcurl"),
        "text/vnd.fly" to listOf("fly"),
        "text/vnd.fmi.flexstor" to listOf("flx"),
        "text/vnd.graphviz" to listOf("gv"),
        "text/vnd.in3d.3dml" to listOf("3dml"),
        "text/vnd.in3d.spot" to listOf("spot"),
        "text/vnd.iptc.anpa" to listOf("anpa"),
        "text/vnd.sun.j2me.app-descriptor" to listOf("jad"),
        "text/vnd.wap.wml" to listOf("wml"),
        "text/vnd.wap.wmlscript" to listOf("wmls"),
        "text/vtt" to listOf("vtt"),
        "text/x-awk" to listOf("awk"),
        "text/x-basic" to listOf("bas", "Bas", "BAS"),
        "text/x-c++hdr" to listOf("hpp", "hxx", "hh", "H", "h++", "hp", "HPP"),
        "text/x-c++src" to listOf("cpp", "cxx", "cc", "C", "c++", "CPP"),
        "text/x-cgi" to listOf("cgi"),
        "text/x-chdr" to listOf("h"),
        "text/x-clojure" to listOf("clj"),
        "text/x-coffeescript" to listOf("coffee"),
        "text/x-csrc" to listOf("c"),
        "text/x-csharp" to listOf("cs"),
        "text/x-cobol" to listOf("cbl", "Cbl", "CBL", "cob", "Cob", "COB"),
        "text/x-coldfusion" to listOf("cfm", "cfml", "cfc"),
        "text/x-common-lisp" to listOf("cl", "jl", "lisp", "lsp"),
        "text/x-diff" to listOf("diff", "patch"),
        "text/x-eiffel" to listOf("e"),
        "text/x-emacs-lisp" to listOf("el"),
        "text/x-erlang" to listOf("erl"),
        "text/x-expect" to listOf("exp"),
        "text/x-forth" to listOf("4th"),
        "text/x-fortran" to listOf("f", "F", "for", "f77", "f90"),
        "text/x-go" to listOf("go"),
        "text/x-groovy" to listOf("groovy"),
        "text/x-haskell" to listOf("hs", "lhs"),
        "text/x-idl" to listOf("idl"),
        "text/x-ini" to listOf("ini"),
        "text/x-java-source" to listOf("java"),
        "text/x-java-properties" to listOf("properties"),
        "text/x-jsp" to listOf("jsp"),
        "text/x-less" to listOf("less"),
        "text/x-lex" to listOf("l"),
        "text/x-log" to listOf("log"),
        "text/x-lua" to listOf("lua"),
        "text/x-ml" to listOf("ml"),
        "application/x-matlab-data" to listOf("mat"),
        "text/x-modula" to listOf("m3", "i3", "mg", "ig"),
        "text/x-objcsrc" to listOf("m"),
        "text/x-ocaml" to listOf("ocaml", "mli"),
        "text/x-pascal" to listOf("p", "pp", "pas", "PAS", "dpr"),
        "text/x-perl" to listOf("pl", "pm", "al", "perl"),
        "text/x-php" to listOf("php", "php3", "php4"),
        "text/x-prolog" to listOf("pro"),
        "text/x-python" to listOf("py"),
        "text/x-rst" to listOf("rest", "rst", "restx"),
        "text/x-rexx" to listOf("rexx"),
        "text/x-ruby" to listOf("rb"),
        "text/x-scala" to listOf("scala"),
        "text/x-scheme" to listOf("scm"),
        "text/x-sed" to listOf("sed"),
        "text/x-sql" to listOf("sql"),
        "text/x-setext" to listOf("etx"),
        "text/x-stsrc" to listOf("st"),
        "text/x-tcl" to listOf("itk", "tcl", "tk"),
        "text/x-uuencode" to listOf("uu"),
        "text/x-vbasic" to listOf("cls", "Cls", "CLS", "frm", "Frm", "FRM"),
        "text/x-vbdotnet" to listOf("vb"),
        "text/x-vbscript" to listOf("vbs"),
        "text/x-vcalendar" to listOf("vcs"),
        "text/x-vcard" to listOf("vcf"),
        "text/x-verilog" to listOf("v"),
        "text/x-vhdl" to listOf("vhd", "vhdl"),
        "text/x-web-markdown" to listOf("md", "mdtext", "mkd", "markdown"),
        "text/x-yacc" to listOf("y"),
        "text/x-yaml" to listOf("yaml", "yml"),
        "video/3gpp" to listOf("3gp"),
        "video/3gpp2" to listOf("3g2"),
        "video/h261" to listOf("h261"),
        "video/h263" to listOf("h263"),
        "video/h264" to listOf("h264"),
        "video/iso.segment" to listOf("m4s"),
        "video/jpeg" to listOf("jpgv"),
        "video/mj2" to listOf("mj2", "mjp2"),
        "video/mp4" to listOf("mp4", "mp4v", "mpg4"),
        "video/mpeg" to listOf("mpeg", "mpg", "mpe", "m1v", "m2v"),
        "video/ogg" to listOf("ogv"),
        "video/x-dirac" to listOf("drc"),
        "video/x-ogm" to listOf("ogm"),
        "video/quicktime" to listOf("qt", "mov"),
        "video/vnd.fvt" to listOf("fvt"),
        "video/vnd.mpegurl" to listOf("mxu", "m4u"),
        "video/vnd.ms-playready.media.pyv" to listOf("pyv"),
        "video/vnd.vivo" to listOf("viv"),
        "video/x-f4v" to listOf("f4v"),
        "video/x-flc" to listOf("flc"),
        "video/x-fli" to listOf("fli"),
        "video/x-flv" to listOf("flv"),
        "video/x-jng" to listOf("jng"),
        "video/x-m4v" to listOf("m4v"),
        "video/x-mng" to listOf("mng"),
        "video/x-ms-asf" to listOf("asf"),
        "application/x-ms-asx" to listOf("asx"),
        "video/x-ms-wm" to listOf("wm"),
        "video/x-ms-wmv" to listOf("wmv"),
        "video/x-ms-wmx" to listOf("wmx"),
        "video/x-ms-wvx" to listOf("wvx"),
        "video/x-msvideo" to listOf("avi"),
        "video/x-sgi-movie" to listOf("movie"),
        "video/x-matroska" to listOf("mkv"),
        "audio/x-matroska" to listOf("mka"),
        "video/webm" to listOf("webm"),
        "x-conference/x-cooltalk" to listOf("ice"),
        "application/x-fictionbook+xml" to listOf("fb2"),
        "text/x-asciidoc" to listOf("asciidoc", "adoc", "ad", "ad.txt", "adoc.txt"),
        "text/x-d" to listOf("d"),
        "text/x-haml" to listOf("haml"),
        "text/x-haxe" to listOf("hx"),
        "application/x-xliff+xml" to listOf("xlf", "xliff"),
        "application/x-xliff+zip" to listOf("xlz"),
        "text/x-rsrc" to listOf("r"),
    )

    val extensionToMimeType = mutableMapOf<String, String>().apply {
        mimeTypeToExtensions.forEach { (mimeType, extensions) ->
            extensions.forEach { put(it, mimeType) }
        }
    }.toMap()
}
