package fe.linksheet.feature.systeminfo.device

object `Samsung A02s running Android 12` : Device(
    codename = "a02q",
    fingerprint = "samsung/a02qsq/a02q:12/SP1A.210812.016/A025VSQS6CXF3:user/release-keys",
    buildProperties = parseTestBuildProperties("""
    ####################################
    # from generate-common-build-props
    # These properties identify this partition image.
    ####################################
    ro.product.system.brand=samsung
    ro.product.system.device=a02q
    ro.product.system.manufacturer=samsung
    ro.product.system.model=SM-A025V
    ro.product.system.name=a02qsq
    ro.system.product.cpu.abilist=armeabi-v7a,armeabi
    ro.system.product.cpu.abilist32=armeabi-v7a,armeabi
    ro.system.product.cpu.abilist64=
    ro.system.build.date=Tue Jun 11 20:01:13 KST 2024
    ro.system.build.date.utc=1718103673
    ro.system.build.fingerprint=samsung/a02qsq/a02q:12/SP1A.210812.016/A025VSQS6CXF3:user/release-keys
    ro.system.build.id=SP1A.210812.016
    ro.system.build.tags=release-keys
    ro.system.build.type=user
    ro.system.build.version.incremental=A025VSQS6CXF3
    ro.system.build.version.release=12
    ro.system.build.version.release_or_codename=12
    ro.system.build.version.sdk=31
    ####################################
    # from out/target/product/a02q/obj/PACKAGING/system_build_prop_intermediates/buildinfo.prop
    ####################################
    # begin build properties
    # autogenerated by buildinfo.sh
    ro.build.id=SP1A.210812.016
    ro.build.display.id=SP1A.210812.016.A025VSQS6CXF3
    ro.build.keys=test-keys
    ro.build.display_build_number=true
    ro.build.version.incremental=A025VSQS6CXF3
    ro.build.version.sdk=31
    ro.build.version.preview_sdk=0
    ro.build.version.preview_sdk_fingerprint=REL
    ro.build.version.codename=REL
    ro.build.version.all_codenames=REL
    ro.build.version.release=12
    ro.build.version.release_or_codename=12
    ro.build.version.security_patch=2024-05-01
    ro.build.version.base_os=samsung/a02qsq/a02q:12/SP1A.210812.016/A025VSQU4CWF1:user/release-keys
    ro.build.version.security_index=1
    ro.build.version.min_supported_target_sdk=23
    ro.build.date=Tue Jun 11 20:01:13 KST 2024
    ro.build.date.utc=1718103673
    ro.build.type=user
    ro.build.user=dpi
    ro.build.host=SWDK6623
    ro.build.tags=release-keys
    ro.build.flavor=a02qsq-user
    # ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,
    # use ro.product.cpu.abilist instead.
    ro.product.cpu.abi=armeabi-v7a
    ro.product.cpu.abi2=armeabi
    ro.product.locale=en-US
    ro.wifi.channels=
    # ro.build.product is obsolete; use ro.product.device
    # ro.product.name/ro.product.device should use PRODUCT_MODEL in case of jpn model
    ro.build.product=a02q
    # Do not try to parse description or thumbprint
    ro.build.description=a02qsq-user 12 SP1A.210812.016 A025VSQS6CXF3 release-keys
    # Samsung Specific Properties
    ro.build.PDA=A025VSQS6CXF3
    ro.build.changelist=24348486
    ro.product_ship=true
    ro.build.official.release=true
    ro.build.2ndbrand=true
    ro.config.rm_preload_enabled=1
    ro.build.characteristics=phone
    # end build properties
    ####################################
    # from device/qcom/msm8953_64/system.prop
    ####################################
    #
    # system.prop for msm8953
    #
    rild.libpath=/vendor/lib64/libril-qc-qmi-1.so
    rild.libargs=-d /dev/smd0
    persist.rild.nitz_plmn=
    persist.rild.nitz_long_ons_0=
    persist.rild.nitz_long_ons_1=
    persist.rild.nitz_long_ons_2=
    persist.rild.nitz_long_ons_3=
    persist.rild.nitz_short_ons_0=
    persist.rild.nitz_short_ons_1=
    persist.rild.nitz_short_ons_2=
    persist.rild.nitz_short_ons_3=
    ril.subscription.types=NV,RUIM
    DEVICE_PROVISIONED=1
    #
    # Set network mode to (T/L/G/W/1X/EVDO, T/L/G/W/1X/EVDO) for 7+7 mode device on DSDS mode
    #
    # Removed by post_process_props.py because ro.telephony.default_network is a disallowed key
    #ro.telephony.default_network=22,22
    debug.sf.enable_hwc_vds=1
    debug.sf.hw=0
    debug.sf.latch_unsignaled=1
    debug.egl.hw=0
    persist.hwc.mdpcomp.enable=true
    debug.mdpcomp.logs=0
    dalvik.vm.heapsize=36m
    dev.pm.dyn_samplingrate=1
    persist.demo.hdmirotationlock=false
    debug.enable.sglscale=1
    debug.gralloc.enable_fb_ubwc=1
    debug.sf.recomputecrop=0
    #Disable Skip Validate
    sdm.debug.disable_skip_validate=1
    #Property to enable display default color mode
    vendor.display.enable_default_color_mode=1
    # Display Properties as per treble compliance
    vendor.gralloc.enable_fb_ubwc=1
    vendor.display.disable_skip_validate=1
    #ro.hdmi.enable=true
    #
    # system props for the cne module
    #
    persist.vendor.cne.feature=1
    #system props for the MM modules
    media.msm8956hw=0
    mm.enable.smoothstreaming=true
    mmp.enable.3g2=true
    media.aac_51_output_enabled=true
    av.debug.disable.pers.cache=1
    media.settings.xml=/vendor/etc/media_profiles_vendor.xml
    #minimum duration for offload playback in secs
    audio.offload.min.duration.secs=30
    #enable offload audio video playback by default
    audio.offload.video=true
    #enable music through deep buffer
    audio.deep_buffer.media=true
    #set AudioFlinger client heap size
    ro.af.client_heap_size_kbyte=7168
    # Reduce client buffer size for fast audio output tracks
    af.fast_track_multiplier=1
    #codecs:(PARSER_)AAC AC3 AMR_NB AMR_WB ASF AVI DTS FLV 3GP 3G2 MKV MP2PS MP2TS MP3 OGG QCP WAV FLAC AIFF APE
    vendor.mm.enable.qcom_parser=1048575
    #
    # system props for the data modules
    #
    # Removed by post_process_props.py because ro.vendor.use_data_netmgrd is a disallowed key
    #ro.vendor.use_data_netmgrd=true
    persist.data.netmgrd.qos.enable=true
    persist.vendor.data.mode=concurrent
    #system props for time-services
    persist.timed.enable=true
    #system prop for Bluetooth
    #ro.bluetooth.library_name=libbluetooth_qti.so
    # System property for cabl
    ro.qualcomm.cabl=2
    ro.vendor.display.cabl=2
    #
    # System props for telephony
    # System prop to turn on CdmaLTEPhone always
    # Removed by post_process_props.py because telephony.lteOnCdmaDevice is a disallowed key
    #telephony.lteOnCdmaDevice=1
    #Simulate sdcard on /data/media
    #
    persist.fuse_sdcard=true
    #System property for FM transmitter
    ro.fm.transmitter=false
    #property to enable user to access Google WFD settings
    persist.debug.wfd.enable=1
    #property to enable VDS WFD solution
    persist.hwc.enable_vds=1
    #selects CoreSight configuration to enable
    persist.debug.coresight.config=stm-events
    #selects Console configuration to enable
    persist.console.silent.config=1
    #property to enable narrow search range for video encoding
    vendor.vidc.enc.disable_bframes=1
    vendor.vidc.disable.split.mode=1
    vendor.vidc.dec.downscalar_width=1920
    vendor.vidc.dec.downscalar_height=1088
    # system prop for UBWC
    vendor.video.disable.ubwc=1
    # disable PQ feature by default
    vendor.vidc.enc.disable.pq=true
    # Additional buffers shared between Camera and Video
    vidc.enc.dcvs.extra-buff-count=2
    # system property to accelerate Progressive Download using STA
    persist.mm.sta.enable=0
    #property to enable fingerprint
    persist.qfp=false
    #HWUI properties
    ro.hwui.texture_cache_size=72
    ro.hwui.layer_cache_size=48
    ro.hwui.r_buffer_cache_size=8
    ro.hwui.path_cache_size=32
    ro.hwui.gradient_cache_size=1
    ro.hwui.drop_shadow_cache_size=6
    ro.hwui.texture_cache_flushrate=0.4
    ro.hwui.text_small_cache_width=1024
    ro.hwui.text_small_cache_height=1024
    ro.hwui.text_large_cache_width=2048
    ro.hwui.text_large_cache_height=1024
    # set cutoff voltage to 3400mV
    ro.cutoff_voltage_mv=3400
    #set device emmc size
    ro.emmc_size=16GB
    #force HAL1 for below packages
    vendor.camera.hal1.packagelist=com.skype.raider,com.google.android.talk
    #Enable FR27607-RIL to send ONLINE cmd in bootup
    #persist.radio.poweron_opt=1
    #low power mode for camera
    vendor.camera.lowpower.record.enable=1
    #properties for limiting preview size in camera
    persist.vendor.camera.display.umax=1920x1080
    persist.vendor.camera.display.lmax=1280x720
    #expose aux camera for below packages
    vendor.camera.aux.packagelist=org.codeaurora.snapcam
    #set cutoff voltage to 3400mV
    ro.cutoff_voltage_mv=3400
    ####################################
    # from device/Huaqin/hs50_common_32/system.prop
    ####################################
    #
    # system.prop for HS50 common 32p/64k
    #
    #HS70 code to make hs70 be compatible by chengzhi at 2019/10/11 start
    persist.vendor.camera.expose.aux=1
    #HS70 code to make hs70 be compatible by chengzhi at 2019/10/11 end
    #huaqin modify for SR-ZQL1695-01-65 by longteng at 2019/10/23 start
    persist.sys.camera.camera2=true
    #huaqin modify for SR-ZQL1695-01-65 by longteng at 2019/10/23 end
    #HS70 code for P191101-04645 by zhangle at 20191128 start
    #vendor.camera.aux.packagelist=org.codeaurora.snapcam,com.sec.android.app.camera,com.val.hardware
    #HS70 code for P191101-04645 by zhangle at 20191128 start
    #HS50 code for P201002-01520 by gaozhengwei at 2020/10/29 start
    vendor.display.idle_time=1000
    #HS50 code for P201002-01520 by gaozhengwei at 2020/10/29 end
    #HS50 code for OLYMPICO1S-13 by shiyang at 2021/03/24 start
    ro.vendor.cam.name=HS50
    #HS50 code for OLYMPICO1S-13 by shiyang at 2020/03/24 end
    ####################################
    # from variable ADDITIONAL_SYSTEM_PROPERTIES
    ####################################
    # Removed by post_process_props.py because ro.product.first_api_level is a disallowed key
    #ro.product.first_api_level=29
    ro.treble.enabled=true
    ro.actionable_compatible_property.enabled=true
    ro.postinstall.fstab.prefix=/system
    ro.build.version.sem=3101
    ro.build.version.sep=130100
    ro.build.version.oneui=40100
    ro.system.build.version.sehi=3101
    persist.log.semlevel=0xFFFFFF00
    persist.log.level=0xFFFFFFFF
    ro.build.selinux=1
    ro.config.dmverity=G
    ro.oem_unlock_supported=1
    ro.kernel.qemu=0
    ro.secure=1
    security.perf_harden=1
    ro.adb.secure=1
    ro.allow.mock.location=0
    ro.binary.type=user
    ro.debuggable=0
    dalvik.vm.lockprof.threshold=500
    net.bt.name=Android
    ro.vendor.qti.va_aosp.support=1
    persist.device_config.runtime_native_boot.enable_generational_cc=false
    ####################################
    # from variable PRODUCT_SYSTEM_PROPERTIES
    ####################################
    log.tag.ConnectivityManager=D
    log.tag.ConnectivityService=D
    log.tag.NetworkLogger=D
    log.tag.IptablesRestoreController=D
    log.tag.ClatdController=D
    ro.telephony.iwlan_operation_mode=legacy
    debug.atrace.tags.enableflags=0
    persist.traced.enable=1
    external_storage.cross_user.enabled=1
    dalvik.vm.image-dex2oat-Xms=64m
    dalvik.vm.image-dex2oat-Xmx=64m
    dalvik.vm.dex2oat-Xms=64m
    dalvik.vm.dex2oat-Xmx=512m
    dalvik.vm.finalizer-timeout-ms=60000
    dalvik.vm.usejit=true
    dalvik.vm.usejitprofiles=true
    dalvik.vm.dexopt.secondary=true
    dalvik.vm.dexopt.thermal-cutoff=2
    dalvik.vm.appimageformat=lz4
    ro.dalvik.vm.native.bridge=0
    pm.dexopt.first-boot=verify
    pm.dexopt.boot-after-ota=verify
    pm.dexopt.post-boot=extract
    pm.dexopt.install=speed-profile
    pm.dexopt.install-fast=skip
    pm.dexopt.install-bulk=speed-profile
    pm.dexopt.install-bulk-secondary=verify
    pm.dexopt.install-bulk-downgraded=verify
    pm.dexopt.install-bulk-secondary-downgraded=extract
    pm.dexopt.bg-dexopt=speed-profile
    pm.dexopt.ab-ota=speed-profile
    pm.dexopt.inactive=verify
    pm.dexopt.cmdline=verify
    pm.dexopt.shared=speed
    dalvik.vm.dex2oat-updatable-bcp-packages-file=/system/etc/updatable-bcp-packages.txt
    dalvik.vm.dex2oat-resolve-startup-strings=true
    dalvik.vm.dex2oat-max-image-block-size=524288
    dalvik.vm.minidebuginfo=true
    dalvik.vm.dex2oat-minidebuginfo=true
    ro.iorapd.enable=true
    dalvik.vm.madvise.vdexfile.size=104857600
    dalvik.vm.madvise.odexfile.size=104857600
    dalvik.vm.madvise.artfile.size=4294967295
    drm.service.enabled=true
    sys.hqm.support=true
    ro.security.fips.ux=Disabled
    ####################################
    # from variable PRODUCT_SYSTEM_DEFAULT_PROPERTIES
    ####################################
    external_storage.cross_user.enabled=1
    com.samsung.speg.disable=true
    # Auto-added by post_process_props.py
    persist.sys.usb.config=mtp
    # end of file
    """.trimIndent())
)
