/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.content.pm.verify.domain;


import android.content.pm.PackageManager;
import android.os.Parcel;
import android.os.Parcelable;
import android.util.ArrayMap;

import androidx.annotation.NonNull;


import java.util.Map;
import java.util.Set;
import java.util.UUID;

import fe.hidden.HiddenStub;

/**
 * Contains the state of all domains for a given package on device. Used by the domain verification
 * agent to determine the domains declared by a package that need to be verified by comparing
 * against the digital asset links response from the server hosting that domain.
 * <p>
 * These values for each domain can be modified through
 * {@link DomainVerificationManager#setDomainVerificationStatus(UUID,
 * Set, int)}.
 *
 * @hide
 */
public final class DomainVerificationInfo implements Parcelable {

    // Implementation note: the following states are OUTPUT only. Any value that is synonymous with
    // a value in DomainVerificationState must be the EXACT same integer, so that state
    // transformation does not have to occur when sending input into the system, assuming that the
    // system only accepts those synonymous values. The public API values declared here are only
    // used when exiting the system server to prepare this data object for consumption by the
    // verification agent. These constants should only be referenced inside public API classes.
    // The server must use DomainVerificationState.

    /**
     * No response has been recorded by either the system or any verification agent.
     */
    public static final int STATE_NO_RESPONSE = DomainVerificationState.STATE_NO_RESPONSE;

    /**
     * The domain has been explicitly verified.
     */
    public static final int STATE_SUCCESS = DomainVerificationState.STATE_SUCCESS;

    /**
     * Indicates the host cannot be modified by the verification agent.
     */
    public static final int STATE_UNMODIFIABLE = 2;

    /**
     * Indicates the host can be modified by the verification agent and is not considered verified.
     */
    public static final int STATE_MODIFIABLE_UNVERIFIED = 3;

    /**
     * Indicates the host can be modified by the verification agent and is considered verified.
     */
    public static final int STATE_MODIFIABLE_VERIFIED = 4;

    /**
     * The first available custom response code. This and any greater integer, along with {@link
     * #STATE_SUCCESS} are the only values settable by the verification agent. All custom values
     * will be treated as if the domain is unverified.
     */
    public static final int STATE_FIRST_VERIFIER_DEFINED = DomainVerificationState.STATE_FIRST_VERIFIER_DEFINED;


    /**
     * Map of host names to their current state. State is an integer, which defaults to {@link
     * #STATE_NO_RESPONSE}. State can be modified by the domain verification agent (the intended
     * consumer of this API), which can be equal to {@link #STATE_SUCCESS} when verified, or equal
     * to or greater than {@link #STATE_FIRST_VERIFIER_DEFINED} for any unsuccessful response.
     * <p>
     * Hosts which cannot be edited will be assigned {@link #STATE_UNMODIFIABLE}. It is expected
     * that the agent attempt to verify all domains that it can modify the state of.
     */


    private void parcelHostToStateMap(Parcel dest, @SuppressWarnings("unused") int flags) {
        HiddenStub.throwException();
    }

    private Map<String, Integer> unparcelHostToStateMap(Parcel in) {
        return HiddenStub.throwException();
    }


    // Code below generated by codegen v1.0.22.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/frameworks/base/core/java/android/content/pm/verify/domain/DomainVerificationInfo.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    /** @hide */
    public @interface State {}

    /** @hide */
    public static String stateToString(@State int value) {
        return HiddenStub.throwException();
    }

    /**
     * Creates a new DomainVerificationInfo.
     *
     * @param identifier
     *   A domain verification ID for use in later API calls. This represents the snapshot of the
     *   domains for a package on device, and will be invalidated whenever the package changes.
     *   <p>
     *   An exception will be thrown at the next API call that receives the ID if it is no longer
     *   valid.
     *   <p>
     *   The caller may also be notified with a broadcast whenever a package and ID is invalidated, at
     *   which point it can use the package name to evict existing requests with an invalid set ID. If
     *   the caller wants to manually check if any IDs have been invalidate, the {@link
     *   PackageManager#getChangedPackages(int)} API will allow tracking the packages changed since
     *   the last query of this method, prompting the caller to re-query.
     *   <p>
     *   This allows the caller to arbitrarily grant or revoke domain verification status, through
     *   {@link DomainVerificationManager#setDomainVerificationStatus(UUID, Set, int)}.
     * @param packageName
     *   The package name that this data corresponds to.
     * @param hostToStateMap
     *   Map of host names to their current state. State is an integer, which defaults to {@link
     *   #STATE_NO_RESPONSE}. State can be modified by the domain verification agent (the intended
     *   consumer of this API), which can be equal to {@link #STATE_SUCCESS} when verified, or equal
     *   to or greater than {@link #STATE_FIRST_VERIFIER_DEFINED} for any unsuccessful response.
     *   <p>
     *   Hosts which cannot be edited will be assigned {@link #STATE_UNMODIFIABLE}. It is expected
     *   that the agent attempt to verify all domains that it can modify the state of.
     * @hide
     */
    public DomainVerificationInfo(
            @NonNull UUID identifier,
            @NonNull String packageName,
            @NonNull Map<String,Integer> hostToStateMap) {
    }

    /**
     * A domain verification ID for use in later API calls. This represents the snapshot of the
     * domains for a package on device, and will be invalidated whenever the package changes.
     * <p>
     * An exception will be thrown at the next API call that receives the ID if it is no longer
     * valid.
     * <p>
     * The caller may also be notified with a broadcast whenever a package and ID is invalidated, at
     * which point it can use the package name to evict existing requests with an invalid set ID. If
     * the caller wants to manually check if any IDs have been invalidate, the {@link
     * PackageManager#getChangedPackages(int)} API will allow tracking the packages changed since
     * the last query of this method, prompting the caller to re-query.
     * <p>
     * This allows the caller to arbitrarily grant or revoke domain verification status, through
     * {@link DomainVerificationManager#setDomainVerificationStatus(UUID, Set, int)}.
     */
    public @NonNull UUID getIdentifier() {
        return HiddenStub.throwException();
    }

    /**
     * The package name that this data corresponds to.
     */
    public @NonNull String getPackageName() {
        return HiddenStub.throwException();
    }

    /**
     * Map of host names to their current state. State is an integer, which defaults to {@link
     * #STATE_NO_RESPONSE}. State can be modified by the domain verification agent (the intended
     * consumer of this API), which can be equal to {@link #STATE_SUCCESS} when verified, or equal
     * to or greater than {@link #STATE_FIRST_VERIFIER_DEFINED} for any unsuccessful response.
     * <p>
     * Hosts which cannot be edited will be assigned {@link #STATE_UNMODIFIABLE}. It is expected
     * that the agent attempt to verify all domains that it can modify the state of.
     */
    public @NonNull Map<String,Integer> getHostToStateMap() {
        return HiddenStub.throwException();
    }



    @Override
    public void writeToParcel(@NonNull Parcel dest, int flags) {
        HiddenStub.throwException();
    }
    @Override
    public int describeContents() {
        return HiddenStub.throwException();
    }

    public static final Creator<DomainSet> CREATOR = HiddenStub.creator();
}
